/**
 * wild boar
 *
 * Generated by Area Builder on 2026-01-25T16:23:32.941Z
 * Area: Southern Forest (valdoria:forest)
 */

import { NPC, Living, Room } from '../../../lib/std.js';

export class Boar extends NPC {
  constructor() {
    super();
    this.setNPC({
      name: 'wild boar',
      shortDesc: 'a bristly wild boar',
      longDesc: `A stocky wild boar with coarse, bristly brown-grey fur and small,
mean eyes. Its curved tusks look sharp and dangerous, and it snorts
aggressively as it roots through the underbrush. These creatures
are known for their bad temper and surprising ferocity when cornered.`,
      gender: 'neutral',
      respawnTime: 150,
      chatChance: 12,
      chats: [
        { message: 'snorts loudly', type: 'emote' },
        { message: 'roots around in the dirt', type: 'emote' },
        { message: 'paws at the ground aggressively', type: 'emote' },
        { message: 'grunts and snuffles', type: 'emote' },
        { message: 'shakes its bristly hide', type: 'emote' },
      ],
      lootTable: [],
      naturalAttacks: ['gore', 'slam'],
      wandering: true,
      wanderChance: 12,
      wanderAreaRestricted: true,
    });

    // Use auto-balance for level 4 NPC
    this.setLevel(4, 'normal');
    this.maxMana = 0;
    this.mana = 0;

    // Boars are aggressive to players
    this.setAggressive((target: Living) => {
      const player = target as Living & { isConnected?: () => boolean };
      return typeof player.isConnected === 'function';
    });
  }

  // Preserved custom methods
  override async onCreate(): Promise<void> {
      await super.onCreate();
      if (typeof efuns !== 'undefined' && efuns.setHeartbeat) {
        efuns.setHeartbeat(this, true);
      }
    }

  override async onEnter(who: Living, from?: Room): Promise<void> {
      const player = who as Living & { isConnected?: () => boolean };
      if (typeof player.isConnected === 'function') {
        if (Math.random() < 0.5) {
          setTimeout(() => {
            this.emote('snorts aggressively and lowers its head.');
          }, 1200);
        }
      }
    }
}

export default Boar;
