/**
 * Cliff Base
 *
 * Generated by Area Builder on 2026-01-25T16:23:32.932Z
 * Area: Southern Forest (valdoria:forest)
 */

import { Room } from '../../../lib/std.js';
import { ResourceNode } from '../../../std/profession/resource-node.js';

export class CliffBase extends Room {
  constructor() {
    super();
    this.shortDesc = 'Cliff Base';
    this.longDesc = `You stand at the base of a {yellow}rocky cliff{/} that rises steeply
above the forest floor. The cliff face is weathered and cracked, with
{green}vines{/} and {dim}lichens{/} clinging to its surface.

Patches of {cyan}ore{/} glint in the rock where the stone has fractured,
hinting at mineral deposits within. A narrow {dim}ledge{/} zigzags {green}up{/}
the cliff face, offering a possible route for skilled climbers.

The forest trail continues to the {green}west{/}.`;
    this.setMapCoordinates({ x: 4, y: 1, z: 0, area: '/areas/valdoria/forest' });
    this.setTerrain('mountain');
    this.mapIcon = '^';
    this.setupRoom();  }

  private setupRoom(): void {
    // Exits
    this.addExit('southwest', '/areas/valdoria/forest/old_trail');
    this.addSkillGatedExit('up', '/areas/valdoria/forest/cliff_ledge', {
      profession: 'climbing',
      level: 1,
      failMessage: 'The ledge above is too steep. You need climbing level 1.',
    });

  }

  // Preserved custom methods
  override async onCreate(): Promise<void> {
      await super.onCreate();
  
      // Add iron ore deposit at the cliff base
      const ironDeposit = new ResourceNode();
      ironDeposit.initFromDefinition('iron_deposit');
      await ironDeposit.moveTo(this);
    }

  override async onEnter(obj: MudObject, from?: MudObject): Promise<void> {
      const receiver = obj as MudObject & { receive?: (msg: string) => void };
      if (typeof receiver.receive === 'function') {
        receiver.receive('\n{dim}The cliff looms above you, its face spotted with handholds.{/}\n');
      }
    }
}

export default CliffBase;
