/**
 * Cliff Ledge
 *
 * Generated by Area Builder on 2026-01-25T16:23:32.933Z
 * Area: Southern Forest (valdoria:forest)
 */

import { Room } from '../../../lib/std.js';
import type { MudObject } from '../../../std/object.js';
import type { ProfessionPlayer } from '../../../daemons/profession.js';
import { ResourceNode } from '../../../std/profession/resource-node.js';

export class CliffLedge extends Room {
  constructor() {
    super();
    this.shortDesc = 'Cliff Ledge';
    this.longDesc = `You stand on a narrow ledge carved into the cliff face, perhaps
{yellow}fifty feet{/} above the forest floor. The view is spectacular -
the {green}forest canopy{/} stretches out below like a sea of green,
and you can see the {cyan}glint of water{/} from the distant stream.

The rock here is rich with {blue}silver ore{/}, exposed by centuries
of weathering. Mining here would be challenging but rewarding.

The ledge continues upward to the {green}north{/} for skilled climbers.
You can carefully descend {green}down{/} to the cliff base.`;
    this.setMapCoordinates({ x: 5, y: 3, z: 1, area: '/areas/valdoria/forest' });
    this.setTerrain('mountain');
    this.mapIcon = '^';
    this.setupRoom();  }

  private setupRoom(): void {
    // Exits
    // No exits

  }

  // Preserved custom methods
  override async onCreate(): Promise<void> {
      await super.onCreate();
  
      // Add silver vein for mining
      const silverVein = new ResourceNode();
      silverVein.initFromDefinition('silver_vein');
      await silverVein.moveTo(this);
    }

  override async onEnter(obj: MudObject, from?: MudObject): Promise<void> {
      const receiver = obj as MudObject & { receive?: (msg: string) => void };
      if (typeof receiver.receive === 'function') {
        receiver.receive('\n{yellow}You pull yourself onto the ledge, breathing heavily from the climb.{/}\n');
      }
  
      // Award climbing XP for arriving
      try {
        const { getProfessionDaemon } = await import('../../../daemons/profession.js');
        const daemon = getProfessionDaemon();
        daemon.awardXP(obj as ProfessionPlayer, 'climbing', 10);
      } catch {
        // Profession daemon not available
      }
    }
}

export default CliffLedge;
