/**
 * deer
 *
 * Generated by Area Builder on 2026-01-25T16:23:32.942Z
 * Area: Southern Forest (valdoria:forest)
 */

import { NPC } from '../../../lib/std.js';

export class Deer extends NPC {
  constructor() {
    super();
    this.setNPC({
      name: 'deer',
      shortDesc: 'a graceful deer',
      longDesc: `A beautiful deer with a sleek brown coat and large, gentle eyes.
It moves with quiet grace through the forest, pausing occasionally
to nibble on leaves or listen for danger. Its ears swivel constantly,
alert to every sound.`,
      gender: 'neutral',
      respawnTime: 90,
      chatChance: 15,
      chats: [
        { message: 'flicks its tail', type: 'emote' },
        { message: 'nibbles on some leaves', type: 'emote' },
        { message: 'looks around cautiously', type: 'emote' },
        { message: 'stamps a hoof softly', type: 'emote' },
        { message: 'raises its head, sniffing the air', type: 'emote' },
      ],
      lootTable: [],
      wandering: true,
      wanderChance: 15,
      wanderAreaRestricted: true,
    });

    // Use auto-balance for level 2 NPC
    this.setLevel(2, 'normal');
    this.maxMana = 0;
    this.mana = 0;
  }

  // Preserved custom methods
  override async onCreate(): Promise<void> {
      await super.onCreate();
      if (typeof efuns !== 'undefined' && efuns.setHeartbeat) {
        efuns.setHeartbeat(this, true);
      }
    }

  override async onEnter(who: Living, from?: Room): Promise<void> {
      const player = who as Living & { isConnected?: () => boolean };
      if (typeof player.isConnected === 'function') {
        if (Math.random() < 0.4) {
          setTimeout(() => {
            this.emote('raises its head and watches warily.');
          }, 1000);
        }
      }
    }
}

export default Deer;
