/**
 * Hunter\
 *
 * Generated by Area Builder on 2026-01-25T16:23:32.937Z
 * Area: Southern Forest (valdoria:forest)
 */

import { Room } from '../../../lib/std.js';
import { ResourceNode } from '../../../std/profession/resource-node.js';

export class HuntersCamp extends Room {
  constructor() {
    super();
    this.shortDesc = 'Hunter\\';
    this.longDesc = `The remains of a {yellow}hunter's camp{/} occupy this small clearing.
A {dim}stone fire ring{/} holds cold ashes, and a weathered {yellow}lean-to{/}
sags against a tree. Scattered about are signs of hasty departure -
an overturned pot, torn canvas, broken arrows.

{red}Claw marks{/} score the lean-to's wooden frame, and dark stains
on the ground tell a grim story. Whoever camped here left in a
hurry... or didn't leave at all.

The trail leads back {green}west{/} toward the forest path.
{dim}Perhaps there are useful supplies left behind.{/}`;
    this.setMapCoordinates({ x: 4, y: 2, z: 0, area: '/areas/valdoria/forest' });
    this.setTerrain('forest');
    this.mapIcon = 'A';
    this.setupRoom();  }

  private setupRoom(): void {
    // Exits
    this.addExit('west', '/areas/valdoria/forest/old_trail');

  }

  // Preserved custom methods
  override async onCreate(): Promise<void> {
      // Wolves sometimes lurk here
      if (Math.random() < 0.4 && typeof efuns !== 'undefined' && efuns.cloneObject) {
        const wolf = await efuns.cloneObject('/areas/valdoria/forest/wolf');
        if (wolf) await wolf.moveTo(this);
      }

      const kingsblood = new ResourceNode();
      kingsblood.initFromDefinition('kingsblood_bush');
      await kingsblood.moveTo(this);

      const ironwood = new ResourceNode();
      ironwood.initFromDefinition('ironwood_tree');
      await ironwood.moveTo(this);
    }

  override async onEnter(obj: MudObject, from?: MudObject): Promise<void> {
      const receiver = obj as MudObject & { receive?: (msg: string) => void };
      if (typeof receiver.receive === 'function') {
        receiver.receive('\n{dim}An uneasy feeling settles over you as you survey the abandoned camp.{/}\n');
      }
    }
}

export default HuntersCamp;
