/**
 * forest wolf
 *
 * Generated by Area Builder on 2026-01-25T16:23:32.942Z
 * Area: Southern Forest (valdoria:forest)
 */

import { NPC } from '../../../lib/std.js';

export class Wolf extends NPC {
  constructor() {
    super();
    this.setNPC({
      name: 'forest wolf',
      shortDesc: 'a grey forest wolf',
      longDesc: `This is a lean, powerful wolf with thick grey fur and piercing yellow eyes.
Its muscles ripple beneath its coat as it pads silently through the undergrowth.
Sharp teeth glint when it snarls, and its ears are constantly swiveling,
alert for both prey and danger. This is clearly a dangerous predator.`,
      gender: 'neutral',
      respawnTime: 180, // 3 minutes
      chatChance: 10,
      chats: [
        { message: 'growls menacingly', type: 'emote' },
        { message: 'sniffs the air', type: 'emote' },
        { message: 'paces back and forth restlessly', type: 'emote' },
        { message: 'lets out a low, threatening growl', type: 'emote' },
        { message: 'watches you with hungry eyes', type: 'emote' },
        { message: 'raises its hackles', type: 'emote' },
      ],
      lootTable: [
        { itemPath: '/items/quest/wolf_pelt', chance: 65 },
        { itemPath: '/items/quest/wolf_pelt', chance: 30 }, // Chance for second pelt
      ],
      naturalAttacks: ['bite', 'claw'],
      wandering: true,
      wanderChance: 10,
      wanderAreaRestricted: true,
    });

    // Preserved custom code
    // Use auto-balance for level 5 normal NPC
    // Override stats for wolf flavor (fast and tough)
    this.setBaseStat('strength', 12);
    this.setBaseStat('dexterity', 14);
    this.setBaseStat('constitution', 12);
    this.setBaseStat('intelligence', 4);
    this.setBaseStat('wisdom', 10);
    this.setBaseStat('charisma', 6);
    this.setBaseStat('luck', 8);
    // Wolves don't use mana
    this.maxMana = 0;
    this.mana = 0;
    // Wolves are aggressive to players
    this.setAggressive((target: Living) => {
  }

  // Preserved custom methods
  override async onCreate(): Promise<void> {
      await super.onCreate();
  
      if (typeof efuns !== 'undefined' && efuns.setHeartbeat) {
        efuns.setHeartbeat(this, true);
      }
    }

  override async onEnter(who: Living, from?: Room): Promise<void> {
      // Check if it's a player
      const player = who as Living & { isConnected?: () => boolean };
      if (typeof player.isConnected === 'function') {
        // 40% chance to growl at newcomers
        if (Math.random() < 0.4) {
          setTimeout(() => {
            this.emote('turns its attention toward the newcomer and growls.');
          }, 1500);
        }
      }
    }
}

export default Wolf;
