/**
 * Wolf Den
 *
 * Generated by Area Builder on 2026-01-25T16:23:32.940Z
 * Area: Southern Forest (valdoria:forest)
 */

import { Room } from '../../../lib/std.js';

export class WolfDen extends Room {
  constructor() {
    super();
    this.shortDesc = 'Wolf Den';
    this.longDesc = `You've found the wolves' lair - a natural cave formed by massive
boulders leaning against each other, hidden beneath the roots of
fallen trees. The entrance is littered with {dim}gnawed bones{/} and
tufts of {dim}grey fur{/}.

The smell of wolves is overwhelming here - musky and primal.
{red}Yellow eyes{/} gleam from the shadows of the den, and low growls
warn intruders away. This is clearly dangerous territory.

The only way out is {green}north{/}, back toward the ancient oak.
Wolves patrol this area constantly, defending their territory.`;
    this.setMapCoordinates({ x: 2, y: 5, z: 0, area: '/areas/valdoria/forest' });
    this.setTerrain('forest');
    this.mapIcon = 'W';
    this.setupRoom();  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/forest/ancient_oak');

  }

  // Preserved custom methods
  override async onCreate(): Promise<void> {
      await super.onCreate();
  
      // Spawn 2-3 wolves (manual spawning, not via setNpcs)
      if (typeof efuns !== 'undefined' && efuns.cloneObject) {
        const wolfCount = 2 + Math.floor(Math.random() * 2);
        for (let i = 0; i < wolfCount; i++) {
          const wolf = await efuns.cloneObject('/areas/valdoria/forest/wolf');
          if (wolf) {
            this.registerSpawnedNpc(wolf); // Track for respawn coordination
            await wolf.moveTo(this);
          }
        }
      }
    }

  override async onEnter(obj: MudObject, from?: MudObject): Promise<void> {
      const receiver = obj as MudObject & { receive?: (msg: string) => void };
      if (typeof receiver.receive === 'function') {
        receiver.receive('\n{red}You\'ve entered the wolves\' den! Growls echo from all around you!{/}\n');
      }
      this.broadcast(`${obj.shortDesc} has entered the wolves' territory!`, { exclude: [obj] });
    }
}

export default WolfDen;
