/**
 * items/battle axe
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.796Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Weapon } from '../../../lib/std.js';
import { Weapon } from '../../../../std/weapon.js';

export class Items/BattleAxe extends Weapon {
  constructor() {
    super();
    this.shortDesc = 'items/battle axe';
    this.longDesc = `A massive two-handed battle axe with a crescent-shaped head. The
blade is made of thick, tempered steel capable of cleaving through
armor. The long oak shaft is reinforced with iron bands. It's a
weapon that demands strength but rewards with devastating power.`;
    this.addId('axe');
    this.addId('battle axe');
    this.addId('battleaxe');
    this.damageType = 'slashing';
    this.handedness = 'one_handed';
    this.minDamage = 1;
    this.maxDamage = 3;
  }
}

export default Items/BattleAxe;
