/**
 * items/chainmail
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.796Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Armor } from '../../../lib/std.js';
import { Armor } from '../../../../std/armor.js';

export class Items/Chainmail extends Armor {
  constructor() {
    super();
    this.shortDesc = 'items/chainmail';
    this.longDesc = `A shirt of interlocking metal rings that provides solid protection
against slashing attacks. Each ring has been individually riveted,
a sign of quality craftsmanship. The mail extends to mid-thigh and
includes a coif for head protection.`;
    this.addId('armor');
    this.addId('chainmail');
    this.addId('chain');
    this.addId('mail');
    this.addId('shirt');
    this.weight = 12;
    this.slot = 'chest';
    this.armor = 1;
  }
}

export default Items/Chainmail;
