/**
 * Greater Healing Potion
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.797Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Consumable } from '../../../../std/consumable.js';

export class GreaterHealingPotion extends Consumable {
  constructor() {
    super();
    this.shortDesc = 'a greater healing potion';
    this.longDesc = `A large glass vial containing a deep scarlet liquid that seems to
glow from within. The potion radiates warmth and the scent of
powerful herbs. When consumed, it provides significant healing.`;
    this.addId('potion');
    this.addId('healing potion');
    this.addId('greater healing potion');
    this.addId('health potion');
    this.setConsumable({
      type: 'potion',
      healHp: 50,
      portions: 1,
      consumeMessage: 'You drink the potion. Powerful healing magic surges through you.',
      roomMessage: '{name} drinks a greater healing potion.',
    });
  }
}

export default GreaterHealingPotion;
