/**
 * items/greater healing potion
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.797Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Item } from '../../../lib/std.js';
import { HealingPotion } from '../../../../std/consumables/healing_potion.js';

export class Items/GreaterHealingPotion extends Item {
  constructor() {
    super();
    this.shortDesc = 'a items/greater healing potion';
    this.longDesc = `A greater quality potion.`;
    this.addId('potion');
    this.addId('healing');
    this.addId('health');
  }
}

export default Items/GreaterHealingPotion;
