/**
 * Iron Sword
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.798Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Weapon } from '../../../../std/weapon.js';

export class IronSword extends Weapon {
  constructor() {
    super();
    this.shortDesc = 'an iron sword';
    this.longDesc = `A sturdy iron sword with a double-edged blade. The crossguard is simple
but functional, and the leather-wrapped grip shows signs of quality
craftsmanship. While not exceptional, it's a reliable weapon for any
adventurer.`;
    this.addId('sword');
    this.addId('iron sword');
    this.addId('blade');
    this.damageType = 'slashing';
    this.handedness = 'one_handed';
    this.minDamage = 4;
    this.maxDamage = 8;
    this.weight = 4;
  }
}

export default IronSword;
