/**
 * Iron Shield
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.798Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Armor } from '../../../../std/armor.js';

export class IronShield extends Armor {
  constructor() {
    super();
    this.shortDesc = 'an iron shield';
    this.longDesc = `A round iron shield about two feet in diameter. The face is
slightly convex with a central boss, and the grip is made of
thick leather wrapped around an iron bar. Scratches and dents
on the surface attest to its proven reliability in battle.`;
    this.addId('shield');
    this.addId('iron shield');
    this.weight = 6;
    this.slot = 'off_hand';
    this.armor = 3;
  }
}

export default IronShield;
