/**
 * Iron Helm
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.798Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Armor } from '../../../../std/armor.js';

export class IronHelm extends Armor {
  constructor() {
    super();
    this.shortDesc = 'an iron helm';
    this.longDesc = `A simple iron helmet with a nose guard and ear flaps. The inside is
lined with leather padding for comfort. While it somewhat limits
peripheral vision, the protection it offers to the head is
invaluable in combat.`;
    this.addId('helm');
    this.addId('helmet');
    this.addId('iron helm');
    this.addId('iron helmet');
    this.weight = 3;
    this.slot = 'head';
    this.armor = 2;
  }
}

export default IronHelm;
