/**
 * items/iron dagger
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.797Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Weapon } from '../../../lib/std.js';
import { Weapon } from '../../../../std/weapon.js';

export class Items/IronDagger extends Weapon {
  constructor() {
    super();
    this.shortDesc = 'items/iron dagger';
    this.longDesc = `A simple but effective dagger with a sharp iron blade. The handle is
wrapped in dark leather for a secure grip. Light and quick, it's
perfect as a backup weapon or for those who prefer speed over raw
power.`;
    this.addId('dagger');
    this.addId('iron dagger');
    this.addId('knife');
    this.damageType = 'slashing';
    this.handedness = 'one_handed';
    this.minDamage = 1;
    this.maxDamage = 3;
  }
}

export default Items/IronDagger;
