/**
 * Leather Armor
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.798Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Armor } from '../../../../std/armor.js';

export class LeatherArmor extends Armor {
  constructor() {
    super();
    this.shortDesc = 'a leather armor vest';
    this.longDesc = `A vest of hardened leather reinforced with metal studs at critical
points. The leather has been treated and cured to provide decent
protection while remaining flexible enough for full freedom of
movement. Ideal for scouts and rogues who value mobility.`;
    this.addId('armor');
    this.addId('leather');
    this.addId('leather armor');
    this.addId('vest');
    this.weight = 5;
    this.slot = 'chest';
    this.armor = 2;
  }
}

export default LeatherArmor;
