/**
 * Lesser Healing Potion
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.798Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Consumable } from '../../../../std/consumable.js';

export class LesserHealingPotion extends Consumable {
  constructor() {
    super();
    this.shortDesc = 'a lesser healing potion';
    this.longDesc = `A small glass vial containing a ruby-red liquid that glows faintly.
The potion swirls with tiny sparkles of light. When consumed, it
provides a mild healing effect.`;
    this.addId('potion');
    this.addId('healing potion');
    this.addId('lesser healing potion');
    this.addId('health potion');
    this.setConsumable({
      type: 'potion',
      healHp: 15,
      portions: 1,
      consumeMessage: 'You drink the potion. A warm sensation spreads through your body.',
      roomMessage: '{name} drinks a healing potion.',
    });
  }
}

export default LesserHealingPotion;
