/**
 * items/lesser mana potion
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.799Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Item } from '../../../lib/std.js';
import { ManaPotion } from '../../../../std/consumables/mana_potion.js';

export class Items/LesserManaPotion extends Item {
  constructor() {
    super();
    this.shortDesc = 'a items/lesser mana potion';
    this.longDesc = `A lesser quality potion.`;
    this.addId('potion');
    this.addId('mana');
    this.addId('magic');
  }
}

export default Items/LesserManaPotion;
