/**
 * Lesser Mana Potion
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.799Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Consumable } from '../../../../std/consumable.js';

export class LesserManaPotion extends Consumable {
  constructor() {
    super();
    this.shortDesc = 'a lesser mana potion';
    this.longDesc = `A small glass vial containing a shimmering blue liquid that sparkles
with arcane energy. The potion feels cool to the touch and seems to
hum faintly. When consumed, it restores a small amount of mana.`;
    this.addId('potion');
    this.addId('mana potion');
    this.addId('lesser mana potion');
    this.addId('magic potion');
    this.setConsumable({
      type: 'potion',
      healMp: 15,
      portions: 1,
      consumeMessage: 'You drink the potion. Cool energy flows through your mind, restoring your magical reserves.',
      roomMessage: '{name} drinks a mana potion.',
    });
  }
}

export default LesserManaPotion;
