/**
 * Major Healing Potion
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.799Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Consumable } from '../../../../std/consumable.js';

export class MajorHealingPotion extends Consumable {
  constructor() {
    super();
    this.shortDesc = 'a major healing potion';
    this.longDesc = `A sturdy crystal vial containing a brilliant ruby liquid that
blazes with inner fire. The potion hums with magical energy and
trails wisps of crimson mist. When consumed, it provides powerful
healing that can mend even grievous wounds.`;
    this.addId('potion');
    this.addId('healing potion');
    this.addId('major healing potion');
    this.addId('health potion');
    this.setConsumable({
      type: 'potion',
      healHp: 75,
      portions: 1,
      consumeMessage: 'You drink the potion. Brilliant healing energy blazes through your body, knitting wounds closed.',
      roomMessage: '{name} drinks a major healing potion.',
    });
  }
}

export default MajorHealingPotion;
