/**
 * items/newbie sword
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.800Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Weapon } from '../../../lib/std.js';
import { Weapon } from '../../../../std/weapon.js';

export class Items/NewbieSword extends Weapon {
  constructor() {
    super();
    this.shortDesc = 'items/newbie sword';
    this.longDesc = `A well-worn training sword with a dull edge. While not particularly
impressive, it's sturdy enough to serve a new adventurer until they
can afford something better. The leather grip is soft from years of
use by countless beginners.`;
    this.addId('sword');
    this.addId('training sword');
    this.addId('newbie sword');
    this.addId('worn sword');
    this.addId('blade');
    this.damageType = 'slashing';
    this.handedness = 'one_handed';
    this.minDamage = 1;
    this.maxDamage = 3;
  }
}

export default Items/NewbieSword;
