/**
 * items/newbie armor
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.799Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Armor } from '../../../lib/std.js';
import { Armor } from '../../../../std/armor.js';

export class Items/NewbieArmor extends Armor {
  constructor() {
    super();
    this.shortDesc = 'items/newbie armor';
    this.longDesc = `A simple padded vest made of quilted cloth. It offers minimal
protection but is better than nothing for a new adventurer just
starting out. The padding shows signs of repair from previous
owners' training sessions.`;
    this.addId('armor');
    this.addId('vest');
    this.addId('padded vest');
    this.addId('training vest');
    this.addId('newbie armor');
    this.weight = 2;
    this.slot = 'chest';
    this.armor = 1;
  }
}

export default Items/NewbieArmor;
