/**
 * Newbie Helm
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.800Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Armor } from '../../../../std/armor.js';

export class NewbieHelm extends Armor {
  constructor() {
    super();
    this.shortDesc = 'a leather training cap';
    this.longDesc = `A simple leather cap that provides basic head protection. It's
been worn by many training recruits before you, as evidenced by
the scuff marks and slightly stretched fit. Still, it might save
you from a nasty bump.`;
    this.addId('helm');
    this.addId('cap');
    this.addId('leather cap');
    this.addId('training cap');
    this.addId('newbie helm');
    this.addId('hat');
    this.slot = 'head';
    this.armor = 1;
  }
}

export default NewbieHelm;
