/**
 * items/newbie shield
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.800Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Armor } from '../../../lib/std.js';
import { Armor } from '../../../../std/armor.js';

export class Items/NewbieShield extends Armor {
  constructor() {
    super();
    this.shortDesc = 'items/newbie shield';
    this.longDesc = `A round wooden shield reinforced with a simple iron rim. It's
seen better days - the wood is dented and scratched from
countless practice sessions. But it will serve to block a blow
or two while you learn the basics of combat.`;
    this.addId('shield');
    this.addId('wooden shield');
    this.addId('training shield');
    this.addId('newbie shield');
    this.slot = 'chest';
    this.armor = 1;
  }
}

export default Items/NewbieShield;
