/**
 * Standard Mana Potion
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.801Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Consumable } from '../../../../std/consumable.js';

export class StandardManaPotion extends Consumable {
  constructor() {
    super();
    this.shortDesc = 'a mana potion';
    this.longDesc = `A glass vial containing a deep azure liquid that swirls with inner
light. Tiny motes of magical energy dance within the potion. When
consumed, it restores a moderate amount of mana.`;
    this.addId('potion');
    this.addId('mana potion');
    this.addId('standard mana potion');
    this.addId('magic potion');
    this.setConsumable({
      type: 'potion',
      healMp: 30,
      portions: 1,
      consumeMessage: 'You drink the potion. Arcane energy surges through you, replenishing your mana.',
      roomMessage: '{name} drinks a mana potion.',
    });
  }
}

export default StandardManaPotion;
