/**
 * Standard Healing Potion
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.800Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Consumable } from '../../../../std/consumable.js';

export class StandardHealingPotion extends Consumable {
  constructor() {
    super();
    this.shortDesc = 'a healing potion';
    this.longDesc = `A glass vial containing a bright crimson liquid that pulses with
inner light. The potion is warm to the touch and smells faintly
of herbs. When consumed, it provides moderate healing.`;
    this.addId('potion');
    this.addId('healing potion');
    this.addId('standard healing potion');
    this.addId('health potion');
    this.setConsumable({
      type: 'potion',
      healHp: 30,
      portions: 1,
      consumeMessage: 'You drink the potion. Warmth floods through your veins, mending your wounds.',
      roomMessage: '{name} drinks a healing potion.',
    });
  }
}

export default StandardHealingPotion;
