/**
 * items/steel sword
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.801Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Weapon } from '../../../lib/std.js';
import { Weapon } from '../../../../std/weapon.js';

export class Items/SteelSword extends Weapon {
  constructor() {
    super();
    this.shortDesc = 'items/steel sword';
    this.longDesc = `A well-forged steel sword with excellent balance. The blade gleams with
a mirror-like polish, its edge keen enough to split a hair. The pommel
is weighted for better control, and the guard is decorated with simple
but elegant engravings.`;
    this.addId('sword');
    this.addId('steel sword');
    this.addId('blade');
    this.damageType = 'slashing';
    this.handedness = 'one_handed';
    this.minDamage = 1;
    this.maxDamage = 3;
  }
}

export default Items/SteelSword;
