/**
 * Recipe Definitions
 *
 * All crafting recipes for the profession system.
 */

import type { RecipeDefinition } from './types.js';

/**
 * All recipe definitions indexed by ID.
 */
export const RECIPE_DEFINITIONS: Record<string, RecipeDefinition> = {
  // ========== Blacksmithing - Smelting ==========

  smelt_copper: {
    id: 'smelt_copper',
    name: 'Smelt Copper Ingot',
    profession: 'blacksmithing',
    levelRequired: 1,
    ingredients: [
      { materialId: 'copper_ore', quantity: 2 },
      { materialId: 'coal', quantity: 1 },
    ],
    stationRequired: 'forge',
    craftTime: 5,
    resultType: 'material',
    resultConfig: { materialId: 'copper_ingot', quantity: 1 },
    resultQuantity: 1,
    qualityAffected: false,
    xpReward: 15,
    description: 'Smelt copper ore into usable ingots.',
    requiresLearning: false,
  },

  smelt_bronze: {
    id: 'smelt_bronze',
    name: 'Smelt Bronze Ingot',
    profession: 'blacksmithing',
    levelRequired: 10,
    ingredients: [
      { materialId: 'copper_ore', quantity: 2 },
      { materialId: 'tin_ore', quantity: 1 },
      { materialId: 'coal', quantity: 1 },
    ],
    stationRequired: 'forge',
    craftTime: 6,
    resultType: 'material',
    resultConfig: { materialId: 'bronze_ingot', quantity: 1 },
    resultQuantity: 1,
    qualityAffected: false,
    xpReward: 20,
    description: 'Combine copper and tin to create bronze.',
    requiresLearning: false,
  },

  smelt_iron: {
    id: 'smelt_iron',
    name: 'Smelt Iron Ingot',
    profession: 'blacksmithing',
    levelRequired: 20,
    ingredients: [
      { materialId: 'iron_ore', quantity: 2 },
      { materialId: 'coal', quantity: 2 },
    ],
    stationRequired: 'forge',
    craftTime: 8,
    resultType: 'material',
    resultConfig: { materialId: 'iron_ingot', quantity: 1 },
    resultQuantity: 1,
    qualityAffected: false,
    xpReward: 25,
    description: 'Smelt iron ore into sturdy ingots.',
    requiresLearning: false,
  },

  smelt_steel: {
    id: 'smelt_steel',
    name: 'Forge Steel Ingot',
    profession: 'blacksmithing',
    levelRequired: 35,
    ingredients: [
      { materialId: 'iron_ingot', quantity: 2 },
      { materialId: 'coal', quantity: 3 },
    ],
    stationRequired: 'forge',
    craftTime: 12,
    resultType: 'material',
    resultConfig: { materialId: 'steel_ingot', quantity: 1 },
    resultQuantity: 1,
    qualityAffected: false,
    xpReward: 35,
    description: 'Refine iron into superior steel.',
    requiresLearning: false,
  },

  smelt_silver: {
    id: 'smelt_silver',
    name: 'Smelt Silver Ingot',
    profession: 'blacksmithing',
    levelRequired: 35,
    ingredients: [
      { materialId: 'silver_ore', quantity: 2 },
      { materialId: 'coal', quantity: 1 },
    ],
    stationRequired: 'forge',
    craftTime: 8,
    resultType: 'material',
    resultConfig: { materialId: 'silver_ingot', quantity: 1 },
    resultQuantity: 1,
    qualityAffected: false,
    xpReward: 30,
    description: 'Smelt silver ore into gleaming ingots.',
    requiresLearning: false,
  },

  smelt_gold: {
    id: 'smelt_gold',
    name: 'Smelt Gold Ingot',
    profession: 'blacksmithing',
    levelRequired: 50,
    ingredients: [
      { materialId: 'gold_ore', quantity: 2 },
      { materialId: 'coal', quantity: 2 },
    ],
    stationRequired: 'forge',
    craftTime: 10,
    resultType: 'material',
    resultConfig: { materialId: 'gold_ingot', quantity: 1 },
    resultQuantity: 1,
    qualityAffected: false,
    xpReward: 40,
    description: 'Smelt gold ore into precious ingots.',
    requiresLearning: false,
  },

  smelt_mithril: {
    id: 'smelt_mithril',
    name: 'Smelt Mithril Ingot',
    profession: 'blacksmithing',
    levelRequired: 70,
    ingredients: [
      { materialId: 'mithril_ore', quantity: 3 },
      { materialId: 'coal', quantity: 4 },
    ],
    stationRequired: 'forge',
    craftTime: 15,
    resultType: 'material',
    resultConfig: { materialId: 'mithril_ingot', quantity: 1 },
    resultQuantity: 1,
    qualityAffected: false,
    xpReward: 60,
    description: 'Carefully smelt rare mithril ore.',
    requiresLearning: false,
  },

  // ========== Blacksmithing - Weapons ==========

  craft_copper_dagger: {
    id: 'craft_copper_dagger',
    name: 'Copper Dagger',
    profession: 'blacksmithing',
    levelRequired: 1,
    ingredients: [{ materialId: 'copper_ingot', quantity: 1 }],
    stationRequired: 'forge',
    craftTime: 10,
    resultType: 'weapon',
    resultConfig: {
      basePath: '/std/weapon',
      name: 'copper dagger',
      shortDesc: 'a copper dagger',
      longDesc: 'A small dagger forged from copper.',
      minDamage: 3,
      maxDamage: 6,
      damageType: 'piercing',
      weight: 1,
      value: 20,
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 25,
    description: 'A simple copper dagger.',
    requiresLearning: false,
  },

  craft_bronze_sword: {
    id: 'craft_bronze_sword',
    name: 'Bronze Sword',
    profession: 'blacksmithing',
    levelRequired: 15,
    ingredients: [{ materialId: 'bronze_ingot', quantity: 2 }],
    stationRequired: 'forge',
    craftTime: 15,
    resultType: 'weapon',
    resultConfig: {
      basePath: '/std/weapon',
      name: 'bronze sword',
      shortDesc: 'a bronze sword',
      longDesc: 'A sturdy sword forged from bronze.',
      minDamage: 5,
      maxDamage: 10,
      damageType: 'slashing',
      weight: 3,
      value: 50,
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 35,
    description: 'A reliable bronze sword.',
    requiresLearning: false,
  },

  craft_iron_sword: {
    id: 'craft_iron_sword',
    name: 'Iron Sword',
    profession: 'blacksmithing',
    levelRequired: 25,
    ingredients: [{ materialId: 'iron_ingot', quantity: 2 }],
    stationRequired: 'forge',
    craftTime: 18,
    resultType: 'weapon',
    resultConfig: {
      basePath: '/std/weapon',
      name: 'iron sword',
      shortDesc: 'an iron sword',
      longDesc: 'A well-balanced iron sword.',
      minDamage: 7,
      maxDamage: 14,
      damageType: 'slashing',
      weight: 4,
      value: 80,
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 45,
    description: 'A solid iron sword.',
    requiresLearning: false,
  },

  craft_steel_sword: {
    id: 'craft_steel_sword',
    name: 'Steel Sword',
    profession: 'blacksmithing',
    levelRequired: 40,
    ingredients: [{ materialId: 'steel_ingot', quantity: 2 }],
    stationRequired: 'forge',
    craftTime: 25,
    resultType: 'weapon',
    resultConfig: {
      basePath: '/std/weapon',
      name: 'steel sword',
      shortDesc: 'a steel sword',
      longDesc: 'A finely crafted steel sword.',
      minDamage: 10,
      maxDamage: 18,
      damageType: 'slashing',
      weight: 3,
      value: 150,
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 60,
    description: 'A superior steel blade.',
    requiresLearning: false,
  },

  craft_mithril_sword: {
    id: 'craft_mithril_sword',
    name: 'Mithril Sword',
    profession: 'blacksmithing',
    levelRequired: 75,
    ingredients: [{ materialId: 'mithril_ingot', quantity: 3 }],
    stationRequired: 'forge',
    craftTime: 40,
    resultType: 'weapon',
    resultConfig: {
      basePath: '/std/weapon',
      name: 'mithril sword',
      shortDesc: 'a mithril sword',
      longDesc: 'A legendary sword of silvery-blue mithril, light as a feather yet strong as steel.',
      minDamage: 15,
      maxDamage: 25,
      damageType: 'slashing',
      weight: 2,
      value: 500,
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 100,
    description: 'A legendary mithril blade.',
    requiresLearning: false,
  },

  // ========== Blacksmithing - Armor ==========

  craft_iron_chainmail: {
    id: 'craft_iron_chainmail',
    name: 'Iron Chainmail',
    profession: 'blacksmithing',
    levelRequired: 30,
    ingredients: [{ materialId: 'iron_ingot', quantity: 4 }],
    stationRequired: 'forge',
    craftTime: 30,
    resultType: 'armor',
    resultConfig: {
      basePath: '/std/armor',
      name: 'iron chainmail',
      shortDesc: 'iron chainmail armor',
      longDesc: 'A suit of interlocking iron rings providing solid protection.',
      armor: 15,
      slot: 'chest',
      weight: 15,
      value: 200,
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 55,
    description: 'Iron chainmail for the torso.',
    requiresLearning: false,
  },

  craft_steel_plate: {
    id: 'craft_steel_plate',
    name: 'Steel Breastplate',
    profession: 'blacksmithing',
    levelRequired: 50,
    ingredients: [{ materialId: 'steel_ingot', quantity: 5 }],
    stationRequired: 'forge',
    craftTime: 45,
    resultType: 'armor',
    resultConfig: {
      basePath: '/std/armor',
      name: 'steel breastplate',
      shortDesc: 'a steel breastplate',
      longDesc: 'A solid steel breastplate offering excellent protection.',
      armor: 25,
      slot: 'chest',
      weight: 20,
      value: 400,
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 80,
    description: 'A steel breastplate.',
    requiresLearning: false,
  },

  // ========== Woodworking ==========

  saw_oak_plank: {
    id: 'saw_oak_plank',
    name: 'Saw Oak Plank',
    profession: 'woodworking',
    levelRequired: 1,
    ingredients: [{ materialId: 'oak_log', quantity: 1 }],
    stationRequired: 'workbench',
    craftTime: 5,
    resultType: 'material',
    resultConfig: { materialId: 'oak_plank', quantity: 2 },
    resultQuantity: 2,
    qualityAffected: false,
    xpReward: 15,
    description: 'Convert oak logs into planks.',
    requiresLearning: false,
  },

  saw_ash_plank: {
    id: 'saw_ash_plank',
    name: 'Saw Ash Plank',
    profession: 'woodworking',
    levelRequired: 25,
    ingredients: [{ materialId: 'ash_log', quantity: 1 }],
    stationRequired: 'workbench',
    craftTime: 6,
    resultType: 'material',
    resultConfig: { materialId: 'ash_plank', quantity: 2 },
    resultQuantity: 2,
    qualityAffected: false,
    xpReward: 25,
    description: 'Convert ash logs into planks.',
    requiresLearning: false,
  },

  craft_wooden_shield: {
    id: 'craft_wooden_shield',
    name: 'Wooden Shield',
    profession: 'woodworking',
    levelRequired: 10,
    ingredients: [{ materialId: 'oak_plank', quantity: 3 }],
    stationRequired: 'workbench',
    craftTime: 15,
    resultType: 'armor',
    resultConfig: {
      basePath: '/std/armor',
      name: 'wooden shield',
      shortDesc: 'a wooden shield',
      longDesc: 'A simple but sturdy wooden shield.',
      armor: 8,
      slot: 'off_hand',
      weight: 5,
      value: 30,
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 30,
    description: 'A basic wooden shield.',
    requiresLearning: false,
  },

  craft_hunting_bow: {
    id: 'craft_hunting_bow',
    name: 'Hunting Bow',
    profession: 'woodworking',
    levelRequired: 20,
    ingredients: [
      { materialId: 'ash_plank', quantity: 2 },
      { materialId: 'light_leather', quantity: 1 },
    ],
    stationRequired: 'workbench',
    craftTime: 20,
    resultType: 'weapon',
    resultConfig: {
      basePath: '/std/weapon',
      name: 'hunting bow',
      shortDesc: 'a hunting bow',
      longDesc: 'A well-crafted bow of flexible ash wood.',
      minDamage: 6,
      maxDamage: 12,
      damageType: 'piercing',
      weight: 2,
      value: 75,
      handedness: 'two',
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 45,
    description: 'A reliable hunting bow.',
    requiresLearning: false,
  },

  craft_quarterstaff: {
    id: 'craft_quarterstaff',
    name: 'Quarterstaff',
    profession: 'woodworking',
    levelRequired: 5,
    ingredients: [{ materialId: 'oak_log', quantity: 1 }],
    stationRequired: 'workbench',
    craftTime: 10,
    resultType: 'weapon',
    resultConfig: {
      basePath: '/std/weapon',
      name: 'quarterstaff',
      shortDesc: 'a quarterstaff',
      longDesc: 'A simple but effective staff weapon.',
      minDamage: 4,
      maxDamage: 8,
      damageType: 'bludgeoning',
      weight: 4,
      value: 15,
      handedness: 'two',
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 20,
    description: 'A simple wooden staff.',
    requiresLearning: false,
  },

  // ========== Leatherworking ==========

  craft_leather_vest: {
    id: 'craft_leather_vest',
    name: 'Leather Vest',
    profession: 'leatherworking',
    levelRequired: 10,
    ingredients: [{ materialId: 'light_leather', quantity: 4 }],
    stationRequired: 'tanning_rack',
    craftTime: 20,
    resultType: 'armor',
    resultConfig: {
      basePath: '/std/armor',
      name: 'leather vest',
      shortDesc: 'a leather vest',
      longDesc: 'A simple vest of tanned leather.',
      armor: 8,
      slot: 'chest',
      weight: 4,
      value: 40,
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 30,
    description: 'Basic leather protection.',
    requiresLearning: false,
  },

  craft_leather_boots: {
    id: 'craft_leather_boots',
    name: 'Leather Boots',
    profession: 'leatherworking',
    levelRequired: 15,
    ingredients: [{ materialId: 'light_leather', quantity: 2 }],
    stationRequired: 'tanning_rack',
    craftTime: 15,
    resultType: 'armor',
    resultConfig: {
      basePath: '/std/armor',
      name: 'leather boots',
      shortDesc: 'leather boots',
      longDesc: 'Sturdy boots of tanned leather.',
      armor: 4,
      slot: 'feet',
      weight: 2,
      value: 25,
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 25,
    description: 'Basic leather footwear.',
    requiresLearning: false,
  },

  craft_heavy_leather_armor: {
    id: 'craft_heavy_leather_armor',
    name: 'Heavy Leather Armor',
    profession: 'leatherworking',
    levelRequired: 45,
    ingredients: [{ materialId: 'heavy_leather', quantity: 5 }],
    stationRequired: 'tanning_rack',
    craftTime: 35,
    resultType: 'armor',
    resultConfig: {
      basePath: '/std/armor',
      name: 'heavy leather armor',
      shortDesc: 'heavy leather armor',
      longDesc: 'Thick, reinforced leather armor offering substantial protection.',
      armor: 18,
      slot: 'chest',
      weight: 10,
      value: 200,
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 65,
    description: 'Reinforced leather armor.',
    requiresLearning: false,
  },

  // ========== Alchemy ==========

  craft_minor_healing_potion: {
    id: 'craft_minor_healing_potion',
    name: 'Minor Healing Potion',
    profession: 'alchemy',
    levelRequired: 1,
    ingredients: [
      { materialId: 'silverleaf', quantity: 2 },
      { materialId: 'empty_vial', quantity: 1 },
    ],
    stationRequired: 'alchemy_table',
    craftTime: 10,
    resultType: 'consumable',
    resultConfig: {
      basePath: '/std/consumable',
      name: 'minor healing potion',
      shortDesc: 'a minor healing potion',
      longDesc: 'A small vial of red liquid that restores health.',
      effect: 'heal',
      magnitude: 25,
      weight: 0.5,
      value: 15,
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 20,
    description: 'Restores a small amount of health.',
    requiresLearning: false,
  },

  craft_healing_potion: {
    id: 'craft_healing_potion',
    name: 'Healing Potion',
    profession: 'alchemy',
    levelRequired: 25,
    ingredients: [
      { materialId: 'earthroot', quantity: 2 },
      { materialId: 'peacebloom', quantity: 1 },
      { materialId: 'empty_vial', quantity: 1 },
    ],
    stationRequired: 'alchemy_table',
    craftTime: 15,
    resultType: 'consumable',
    resultConfig: {
      basePath: '/std/consumable',
      name: 'healing potion',
      shortDesc: 'a healing potion',
      longDesc: 'A vial of crimson liquid that restores health.',
      effect: 'heal',
      magnitude: 50,
      weight: 0.5,
      value: 35,
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 35,
    description: 'Restores a moderate amount of health.',
    requiresLearning: false,
  },

  craft_mana_potion: {
    id: 'craft_mana_potion',
    name: 'Mana Potion',
    profession: 'alchemy',
    levelRequired: 20,
    ingredients: [
      { materialId: 'mageroyal', quantity: 2 },
      { materialId: 'empty_vial', quantity: 1 },
    ],
    stationRequired: 'alchemy_table',
    craftTime: 12,
    resultType: 'consumable',
    resultConfig: {
      basePath: '/std/consumable',
      name: 'mana potion',
      shortDesc: 'a mana potion',
      longDesc: 'A vial of blue liquid that restores magical energy.',
      effect: 'restore_mana',
      magnitude: 40,
      weight: 0.5,
      value: 40,
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 30,
    description: 'Restores mana.',
    requiresLearning: false,
  },

  craft_strength_elixir: {
    id: 'craft_strength_elixir',
    name: 'Elixir of Strength',
    profession: 'alchemy',
    levelRequired: 40,
    ingredients: [
      { materialId: 'kingsblood', quantity: 2 },
      { materialId: 'earthroot', quantity: 1 },
      { materialId: 'crystal_vial', quantity: 1 },
    ],
    stationRequired: 'alchemy_table',
    craftTime: 20,
    resultType: 'consumable',
    resultConfig: {
      basePath: '/std/consumable',
      name: 'elixir of strength',
      shortDesc: 'an elixir of strength',
      longDesc: 'A potent elixir that temporarily increases physical power.',
      effect: 'buff_strength',
      magnitude: 5,
      duration: 300,
      weight: 0.5,
      value: 75,
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 50,
    description: 'Temporarily boosts strength.',
    requiresLearning: false,
  },

  // ========== Cooking ==========

  cook_grilled_fish: {
    id: 'cook_grilled_fish',
    name: 'Grilled Fish',
    profession: 'cooking',
    levelRequired: 1,
    ingredients: [{ materialId: 'small_fish', quantity: 1 }],
    stationRequired: 'cooking_fire',
    craftTime: 5,
    resultType: 'consumable',
    resultConfig: {
      basePath: '/std/consumable',
      name: 'grilled fish',
      shortDesc: 'a grilled fish',
      longDesc: 'A simply prepared fish, grilled over an open fire.',
      effect: 'heal',
      magnitude: 15,
      weight: 0.5,
      value: 8,
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 15,
    description: 'A simple meal.',
    requiresLearning: false,
  },

  cook_trout_dinner: {
    id: 'cook_trout_dinner',
    name: 'Trout Dinner',
    profession: 'cooking',
    levelRequired: 15,
    ingredients: [
      { materialId: 'trout', quantity: 1 },
      { materialId: 'silverleaf', quantity: 1 },
    ],
    stationRequired: 'cooking_fire',
    craftTime: 10,
    resultType: 'consumable',
    resultConfig: {
      basePath: '/std/consumable',
      name: 'trout dinner',
      shortDesc: 'a trout dinner',
      longDesc: 'A delicious trout seasoned with herbs.',
      effect: 'heal',
      magnitude: 30,
      weight: 0.5,
      value: 20,
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 25,
    description: 'A hearty meal.',
    requiresLearning: false,
  },

  cook_salmon_feast: {
    id: 'cook_salmon_feast',
    name: 'Salmon Feast',
    profession: 'cooking',
    levelRequired: 30,
    ingredients: [
      { materialId: 'salmon', quantity: 1 },
      { materialId: 'earthroot', quantity: 1 },
      { materialId: 'peacebloom', quantity: 1 },
    ],
    stationRequired: 'cooking_fire',
    craftTime: 15,
    resultType: 'consumable',
    resultConfig: {
      basePath: '/std/consumable',
      name: 'salmon feast',
      shortDesc: 'a salmon feast',
      longDesc: 'A magnificent salmon dish that invigorates body and spirit.',
      effect: 'buff_stamina',
      magnitude: 10,
      duration: 600,
      weight: 1,
      value: 50,
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 45,
    description: 'A feast that boosts stamina.',
    requiresLearning: false,
  },

  // ========== Jeweling ==========

  cut_quartz: {
    id: 'cut_quartz',
    name: 'Cut Quartz',
    profession: 'jeweling',
    levelRequired: 1,
    ingredients: [{ materialId: 'rough_quartz', quantity: 1 }],
    stationRequired: 'jeweler_bench',
    craftTime: 8,
    resultType: 'material',
    resultConfig: { materialId: 'cut_quartz', quantity: 1 },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 20,
    description: 'Cut and polish a raw quartz crystal.',
    requiresLearning: false,
  },

  craft_silver_ring: {
    id: 'craft_silver_ring',
    name: 'Silver Ring',
    profession: 'jeweling',
    levelRequired: 35,
    ingredients: [{ materialId: 'silver_ingot', quantity: 1 }],
    stationRequired: 'jeweler_bench',
    craftTime: 15,
    resultType: 'accessory',
    resultConfig: {
      basePath: '/std/equipment',
      name: 'silver ring',
      shortDesc: 'a silver ring',
      longDesc: 'A simple band of polished silver.',
      slot: 'finger',
      weight: 0.1,
      value: 100,
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 40,
    description: 'A simple silver ring.',
    requiresLearning: false,
  },

  craft_gold_amulet: {
    id: 'craft_gold_amulet',
    name: 'Gold Amulet',
    profession: 'jeweling',
    levelRequired: 55,
    ingredients: [
      { materialId: 'gold_ingot', quantity: 2 },
      { materialId: 'rough_ruby', quantity: 1 },
    ],
    stationRequired: 'jeweler_bench',
    craftTime: 25,
    resultType: 'accessory',
    resultConfig: {
      basePath: '/std/equipment',
      name: 'gold amulet',
      shortDesc: 'a gold amulet',
      longDesc: 'A beautiful gold amulet set with a glowing ruby.',
      slot: 'neck',
      weight: 0.2,
      value: 350,
    },
    resultQuantity: 1,
    qualityAffected: true,
    xpReward: 70,
    description: 'A ruby-set gold amulet.',
    requiresLearning: false,
  },
};

/**
 * Get recipe by ID.
 */
export function getRecipe(id: string): RecipeDefinition | undefined {
  return RECIPE_DEFINITIONS[id];
}

/**
 * Get all recipes for a profession.
 */
export function getRecipesByProfession(professionId: string): RecipeDefinition[] {
  return Object.values(RECIPE_DEFINITIONS).filter((r) => r.profession === professionId);
}
