/**
 * Guild Definitions
 *
 * Defines the four starter guilds and all their skills.
 */

import type { GuildDefinition, SkillDefinition, GuildId } from './types.js';

// ==================== FIGHTER GUILD ====================

export const FIGHTER_GUILD: GuildDefinition = {
  id: 'fighter',
  name: 'Fighter Guild',
  description: 'Masters of martial combat, the Fighter Guild trains warriors in the art of melee combat, defense, and weapon mastery. Fighters excel at dealing and absorbing physical damage.',
  primaryStats: ['strength', 'constitution'],
  statRequirements: { strength: 10, constitution: 8 },
  skillTree: [
    { guildLevel: 1, skills: ['fighter:bash', 'fighter:toughness'] },
    { guildLevel: 3, skills: ['fighter:parry'] },
    { guildLevel: 5, skills: ['fighter:power_attack'] },
    { guildLevel: 7, skills: ['fighter:shield_wall'] },
    { guildLevel: 10, skills: ['fighter:cleave'] },
    { guildLevel: 13, skills: ['fighter:battle_cry'] },
    { guildLevel: 16, skills: ['fighter:berserker_rage'] },
    { guildLevel: 20, skills: ['fighter:whirlwind'] },
  ],
  channelColor: 'red',
  motto: 'Strength through steel.',
  guildHallPath: '/areas/guilds/fighter/guild_hall',
};

export const FIGHTER_SKILLS: SkillDefinition[] = [
  {
    id: 'fighter:bash',
    name: 'Bash',
    description: 'A powerful strike that deals extra damage and may stun the target.',
    type: 'combat',
    target: 'single',
    guild: 'fighter',
    guildLevelRequired: 1,
    manaCost: 10,
    cooldown: 8000,
    maxLevel: 100,
    learnCost: 50,
    advanceCostPerLevel: 25,
    effect: {
      baseMagnitude: 15,
      magnitudePerLevel: 0.5,
      damageType: 'bludgeoning',
    },
    useVerb: 'bash',
    useMessage: 'You bash $T with tremendous force!',
    roomMessage: '$N bashes $T with tremendous force!',
  },
  {
    id: 'fighter:toughness',
    name: 'Toughness',
    description: 'Passive ability that increases maximum health.',
    type: 'passive',
    target: 'none',
    guild: 'fighter',
    guildLevelRequired: 1,
    manaCost: 0,
    cooldown: 0,
    maxLevel: 50,
    learnCost: 100,
    advanceCostPerLevel: 50,
    effect: {
      baseMagnitude: 10,
      magnitudePerLevel: 2,
      statModifier: 'constitution',
    },
  },
  {
    id: 'fighter:parry',
    name: 'Parry',
    description: 'Defensive stance that increases dodge chance.',
    type: 'buff',
    target: 'self',
    guild: 'fighter',
    guildLevelRequired: 3,
    manaCost: 15,
    cooldown: 30000,
    maxLevel: 50,
    learnCost: 200,
    advanceCostPerLevel: 40,
    effect: {
      baseMagnitude: 10,
      magnitudePerLevel: 0.5,
      combatStatModifier: 'toDodge',
      duration: 20000,
    },
  },
  {
    id: 'fighter:power_attack',
    name: 'Power Attack',
    description: 'A devastating blow that deals massive damage.',
    type: 'combat',
    target: 'single',
    guild: 'fighter',
    guildLevelRequired: 5,
    manaCost: 25,
    cooldown: 15000,
    maxLevel: 100,
    learnCost: 500,
    advanceCostPerLevel: 60,
    effect: {
      baseMagnitude: 35,
      magnitudePerLevel: 1.0,
      damageType: 'slashing',
    },
    useVerb: 'deliver',
    useMessage: 'You deliver a devastating power attack on $T!',
  },
  {
    id: 'fighter:shield_wall',
    name: 'Shield Wall',
    description: 'Raises your shield to block incoming attacks.',
    type: 'buff',
    target: 'self',
    guild: 'fighter',
    guildLevelRequired: 7,
    manaCost: 20,
    cooldown: 45000,
    maxLevel: 50,
    learnCost: 800,
    advanceCostPerLevel: 80,
    effect: {
      baseMagnitude: 20,
      magnitudePerLevel: 0.8,
      combatStatModifier: 'toBlock',
      duration: 15000,
    },
  },
  {
    id: 'fighter:cleave',
    name: 'Cleave',
    description: 'A sweeping attack that hits all enemies in the room.',
    type: 'combat',
    target: 'room',
    guild: 'fighter',
    guildLevelRequired: 10,
    manaCost: 40,
    cooldown: 20000,
    maxLevel: 100,
    learnCost: 1500,
    advanceCostPerLevel: 100,
    effect: {
      baseMagnitude: 25,
      magnitudePerLevel: 0.8,
      damageType: 'slashing',
    },
    useVerb: 'unleash',
    useMessage: 'You unleash a devastating cleave!',
  },
  {
    id: 'fighter:battle_cry',
    name: 'Battle Cry',
    description: 'A fearsome war cry that increases damage.',
    type: 'buff',
    target: 'self',
    guild: 'fighter',
    guildLevelRequired: 13,
    manaCost: 30,
    cooldown: 60000,
    maxLevel: 50,
    learnCost: 2500,
    advanceCostPerLevel: 120,
    effect: {
      baseMagnitude: 15,
      magnitudePerLevel: 0.5,
      combatStatModifier: 'damageBonus',
      duration: 30000,
    },
    useVerb: 'roar',
    useMessage: 'You roar a fearsome battle cry!',
  },
  {
    id: 'fighter:berserker_rage',
    name: 'Berserker Rage',
    description: 'Enter a berserker rage, greatly increasing damage but reducing defense.',
    type: 'buff',
    target: 'self',
    guild: 'fighter',
    guildLevelRequired: 16,
    manaCost: 50,
    cooldown: 120000,
    maxLevel: 50,
    learnCost: 5000,
    advanceCostPerLevel: 200,
    effect: {
      baseMagnitude: 30,
      magnitudePerLevel: 1.0,
      combatStatModifier: 'damageBonus',
      duration: 20000,
    },
    useVerb: 'enter',
    useMessage: 'You enter a berserker rage! Your eyes burn with fury!',
  },
  {
    id: 'fighter:whirlwind',
    name: 'Whirlwind',
    description: 'Spin in a deadly whirlwind, striking all enemies multiple times.',
    type: 'combat',
    target: 'room',
    guild: 'fighter',
    guildLevelRequired: 20,
    manaCost: 80,
    cooldown: 45000,
    maxLevel: 100,
    learnCost: 10000,
    advanceCostPerLevel: 300,
    effect: {
      baseMagnitude: 50,
      magnitudePerLevel: 1.5,
      damageType: 'slashing',
    },
    useVerb: 'spin',
    useMessage: 'You spin in a deadly whirlwind of steel!',
  },
];

// ==================== MAGE GUILD ====================

export const MAGE_GUILD: GuildDefinition = {
  id: 'mage',
  name: 'Mage Guild',
  description: 'The Mage Guild studies the arcane arts, teaching spellcasters to harness magical energy for devastating attacks and powerful utility spells. Mages excel at dealing magical damage from a distance.',
  primaryStats: ['intelligence', 'wisdom'],
  statRequirements: { intelligence: 12, wisdom: 8 },
  skillTree: [
    { guildLevel: 1, skills: ['mage:magic_missile', 'mage:arcane_knowledge'] },
    { guildLevel: 3, skills: ['mage:fire_bolt'] },
    { guildLevel: 5, skills: ['mage:frost_armor'] },
    { guildLevel: 7, skills: ['mage:lightning'] },
    { guildLevel: 9, skills: ['mage:detect_invisible'] },
    { guildLevel: 10, skills: ['mage:fireball'] },
    { guildLevel: 12, skills: ['mage:invisibility'] },
    { guildLevel: 13, skills: ['mage:teleport'] },
    { guildLevel: 16, skills: ['mage:mana_shield'] },
    { guildLevel: 20, skills: ['mage:meteor_storm'] },
  ],
  channelColor: 'blue',
  motto: 'Knowledge is power.',
  guildHallPath: '/areas/guilds/mage/guild_hall',
};

export const MAGE_SKILLS: SkillDefinition[] = [
  {
    id: 'mage:magic_missile',
    name: 'Magic Missile',
    description: 'A bolt of pure magical energy that never misses.',
    type: 'combat',
    target: 'single',
    guild: 'mage',
    guildLevelRequired: 1,
    manaCost: 10,
    cooldown: 4000,
    maxLevel: 100,
    learnCost: 50,
    advanceCostPerLevel: 20,
    effect: {
      baseMagnitude: 12,
      magnitudePerLevel: 0.4,
      damageType: 'arcane',
    },
    useVerb: 'cast',
    useMessage: 'You cast magic missile at $T!',
  },
  {
    id: 'mage:arcane_knowledge',
    name: 'Arcane Knowledge',
    description: 'Passive mastery of arcane lore increases intelligence.',
    type: 'passive',
    target: 'none',
    guild: 'mage',
    guildLevelRequired: 1,
    manaCost: 0,
    cooldown: 0,
    maxLevel: 50,
    learnCost: 100,
    advanceCostPerLevel: 50,
    effect: {
      baseMagnitude: 2,
      magnitudePerLevel: 0.5,
      statModifier: 'intelligence',
    },
  },
  {
    id: 'mage:fire_bolt',
    name: 'Fire Bolt',
    description: 'A bolt of fire that burns the target.',
    type: 'combat',
    target: 'single',
    guild: 'mage',
    guildLevelRequired: 3,
    manaCost: 20,
    cooldown: 6000,
    maxLevel: 100,
    learnCost: 200,
    advanceCostPerLevel: 35,
    effect: {
      baseMagnitude: 20,
      magnitudePerLevel: 0.6,
      damageType: 'fire',
    },
    useVerb: 'hurl',
    useMessage: 'You hurl a bolt of fire at $T!',
  },
  {
    id: 'mage:frost_armor',
    name: 'Frost Armor',
    description: 'Surrounds you with a shield of ice that increases armor.',
    type: 'buff',
    target: 'self',
    guild: 'mage',
    guildLevelRequired: 5,
    manaCost: 25,
    cooldown: 60000,
    maxLevel: 50,
    learnCost: 500,
    advanceCostPerLevel: 60,
    effect: {
      baseMagnitude: 15,
      magnitudePerLevel: 0.6,
      combatStatModifier: 'armorBonus',
      duration: 120000,
    },
    useVerb: 'conjure',
    useMessage: 'You conjure a shimmering frost armor around yourself!',
  },
  {
    id: 'mage:lightning',
    name: 'Lightning Bolt',
    description: 'A crackling bolt of lightning that strikes instantly.',
    type: 'combat',
    target: 'single',
    guild: 'mage',
    guildLevelRequired: 7,
    manaCost: 35,
    cooldown: 10000,
    maxLevel: 100,
    learnCost: 800,
    advanceCostPerLevel: 80,
    effect: {
      baseMagnitude: 35,
      magnitudePerLevel: 1.0,
      damageType: 'lightning',
    },
    useVerb: 'call down',
    useMessage: 'You call down a bolt of lightning upon $T!',
  },
  {
    id: 'mage:fireball',
    name: 'Fireball',
    description: 'A massive explosion of fire that damages all enemies.',
    type: 'combat',
    target: 'room',
    guild: 'mage',
    guildLevelRequired: 10,
    manaCost: 60,
    cooldown: 20000,
    maxLevel: 100,
    learnCost: 1500,
    advanceCostPerLevel: 100,
    effect: {
      baseMagnitude: 45,
      magnitudePerLevel: 1.0,
      damageType: 'fire',
    },
    useVerb: 'hurl',
    useMessage: 'You hurl a massive fireball that explodes in flames!',
  },
  {
    id: 'mage:teleport',
    name: 'Teleport',
    description: 'Instantly teleport to a known location.',
    type: 'utility',
    target: 'none',
    guild: 'mage',
    guildLevelRequired: 13,
    manaCost: 50,
    cooldown: 300000,
    maxLevel: 20,
    learnCost: 2500,
    advanceCostPerLevel: 200,
    effect: {
      baseMagnitude: 0,
      magnitudePerLevel: 0,
      customHandler: 'teleport',
    },
    useVerb: 'cast',
    useMessage: 'You cast teleport and vanish in a flash of light!',
  },
  {
    id: 'mage:mana_shield',
    name: 'Mana Shield',
    description: 'Creates a shield that absorbs damage using mana.',
    type: 'buff',
    target: 'self',
    guild: 'mage',
    guildLevelRequired: 16,
    manaCost: 40,
    cooldown: 90000,
    maxLevel: 50,
    learnCost: 5000,
    advanceCostPerLevel: 150,
    effect: {
      baseMagnitude: 50,
      magnitudePerLevel: 2,
      duration: 60000,
    },
    useVerb: 'conjure',
    useMessage: 'You conjure a shimmering mana shield around yourself!',
  },
  {
    id: 'mage:meteor_storm',
    name: 'Meteor Storm',
    description: 'Calls down a devastating rain of meteors upon all enemies.',
    type: 'combat',
    target: 'room',
    guild: 'mage',
    guildLevelRequired: 20,
    manaCost: 100,
    cooldown: 60000,
    maxLevel: 100,
    learnCost: 10000,
    advanceCostPerLevel: 300,
    effect: {
      baseMagnitude: 80,
      magnitudePerLevel: 2.0,
      damageType: 'fire',
    },
    useVerb: 'call down',
    useMessage: 'You call down a devastating meteor storm from the heavens!',
  },
  {
    id: 'mage:detect_invisible',
    name: 'Detect Invisible',
    description: 'Grants the ability to see invisible creatures.',
    type: 'buff',
    target: 'self',
    guild: 'mage',
    guildLevelRequired: 9,
    manaCost: 30,
    cooldown: 60000,
    maxLevel: 50,
    learnCost: 1200,
    advanceCostPerLevel: 90,
    effect: {
      baseMagnitude: 1, // Binary effect - either you can see invisible or not
      magnitudePerLevel: 0,
      duration: 300000, // 5 minutes
      effectType: 'see_invisible',
    },
    useVerb: 'cast',
    useMessage: 'You cast detect invisible. Your eyes shimmer with arcane power!',
  },
  {
    id: 'mage:invisibility',
    name: 'Invisibility',
    description: 'Become invisible to normal sight. Requires See Invisible to detect.',
    type: 'buff',
    target: 'self',
    guild: 'mage',
    guildLevelRequired: 12,
    manaCost: 45,
    cooldown: 120000,
    maxLevel: 50,
    learnCost: 2000,
    advanceCostPerLevel: 100,
    effect: {
      baseMagnitude: 70, // VisibilityLevel.INVISIBLE = 70
      magnitudePerLevel: 0.2,
      duration: 180000, // 3 minutes
      effectType: 'invisibility',
    },
    useVerb: 'cast',
    useMessage: 'You cast invisibility and fade from view!',
  },
];

// ==================== THIEF GUILD ====================

export const THIEF_GUILD: GuildDefinition = {
  id: 'thief',
  name: 'Thief Guild',
  description: 'The Thief Guild operates in the shadows, training rogues in the arts of stealth, precision strikes, and cunning. Thieves excel at dealing massive damage from hiding and avoiding detection.',
  primaryStats: ['dexterity', 'luck'],
  statRequirements: { dexterity: 12, luck: 8 },
  skillTree: [
    { guildLevel: 1, skills: ['thief:hide', 'thief:nimble_fingers'] },
    { guildLevel: 3, skills: ['thief:sneak'] },
    { guildLevel: 5, skills: ['thief:backstab'] },
    { guildLevel: 7, skills: ['thief:lockpick'] },
    { guildLevel: 10, skills: ['thief:poison_blade'] },
    { guildLevel: 13, skills: ['thief:pickpocket'] },
    { guildLevel: 16, skills: ['thief:shadow_step'] },
    { guildLevel: 20, skills: ['thief:assassinate'] },
  ],
  channelColor: 'dim',
  motto: 'Unseen. Unheard. Unstoppable.',
  guildHallPath: '/areas/guilds/thief/guild_hall',
};

export const THIEF_SKILLS: SkillDefinition[] = [
  {
    id: 'thief:hide',
    name: 'Hide',
    description: 'Conceal yourself in the shadows. Requires Detect Hidden to see you.',
    type: 'buff',
    target: 'self',
    guild: 'thief',
    guildLevelRequired: 1,
    manaCost: 10,
    cooldown: 10000,
    maxLevel: 100,
    learnCost: 50,
    advanceCostPerLevel: 20,
    effect: {
      baseMagnitude: 50, // VisibilityLevel.HIDDEN = 50
      magnitudePerLevel: 0.3, // Higher skill = harder to detect
      duration: 60000,
      effectType: 'stealth', // Uses stealth effect for visibility system
    },
    useVerb: 'slip',
    useMessage: 'You slip into the shadows...',
  },
  {
    id: 'thief:nimble_fingers',
    name: 'Nimble Fingers',
    description: 'Passive dexterity bonus from constant practice.',
    type: 'passive',
    target: 'none',
    guild: 'thief',
    guildLevelRequired: 1,
    manaCost: 0,
    cooldown: 0,
    maxLevel: 50,
    learnCost: 100,
    advanceCostPerLevel: 50,
    effect: {
      baseMagnitude: 2,
      magnitudePerLevel: 0.5,
      statModifier: 'dexterity',
    },
  },
  {
    id: 'thief:sneak',
    name: 'Sneak',
    description: 'Move silently without alerting others. High perception can detect you.',
    type: 'buff',
    target: 'self',
    guild: 'thief',
    guildLevelRequired: 3,
    manaCost: 15,
    cooldown: 30000,
    maxLevel: 100,
    learnCost: 200,
    advanceCostPerLevel: 35,
    effect: {
      baseMagnitude: 30, // VisibilityLevel.SNEAKING = 30
      magnitudePerLevel: 0.15, // Higher skill = harder to detect
      duration: 120000,
      effectType: 'stealth', // Uses stealth effect for visibility system
    },
    useVerb: 'begin',
    useMessage: 'You begin moving silently...',
  },
  {
    id: 'thief:backstab',
    name: 'Backstab',
    description: 'A devastating strike from behind that deals massive damage.',
    type: 'combat',
    target: 'single',
    guild: 'thief',
    guildLevelRequired: 5,
    manaCost: 20,
    cooldown: 12000,
    maxLevel: 100,
    learnCost: 500,
    advanceCostPerLevel: 60,
    prerequisites: ['thief:hide'],
    effect: {
      baseMagnitude: 50,
      magnitudePerLevel: 1.5,
      damageType: 'piercing',
    },
    useVerb: 'backstab',
    useMessage: 'You emerge from the shadows and drive your blade into $T\'s back!',
  },
  {
    id: 'thief:lockpick',
    name: 'Lockpick',
    description: 'Attempt to pick a lock.',
    type: 'utility',
    target: 'object',
    guild: 'thief',
    guildLevelRequired: 7,
    manaCost: 10,
    cooldown: 5000,
    maxLevel: 100,
    learnCost: 800,
    advanceCostPerLevel: 40,
    effect: {
      baseMagnitude: 10,
      magnitudePerLevel: 1,
      customHandler: 'lockpick',
    },
    useVerb: 'work on',
    useMessage: 'You work on the lock with your picks...',
  },
  {
    id: 'thief:poison_blade',
    name: 'Poison Blade',
    description: 'Coat your weapon in deadly poison.',
    type: 'buff',
    target: 'self',
    guild: 'thief',
    guildLevelRequired: 10,
    manaCost: 30,
    cooldown: 60000,
    maxLevel: 50,
    learnCost: 1500,
    advanceCostPerLevel: 80,
    effect: {
      baseMagnitude: 5,
      magnitudePerLevel: 0.5,
      damageType: 'poison',
      duration: 180000,
    },
    useVerb: 'coat',
    useMessage: 'You coat your blade with deadly poison...',
  },
  {
    id: 'thief:pickpocket',
    name: 'Pickpocket',
    description: 'Attempt to steal gold from a target.',
    type: 'utility',
    target: 'single',
    guild: 'thief',
    guildLevelRequired: 13,
    manaCost: 20,
    cooldown: 30000,
    maxLevel: 100,
    learnCost: 2500,
    advanceCostPerLevel: 100,
    effect: {
      baseMagnitude: 10,
      magnitudePerLevel: 2,
      customHandler: 'pickpocket',
    },
    useVerb: 'reach for',
    useMessage: 'You deftly reach for $T\'s coin purse...',
  },
  {
    id: 'thief:shadow_step',
    name: 'Shadow Step',
    description: 'Instantly teleport behind your target.',
    type: 'utility',
    target: 'single',
    guild: 'thief',
    guildLevelRequired: 16,
    manaCost: 40,
    cooldown: 45000,
    maxLevel: 50,
    learnCost: 5000,
    advanceCostPerLevel: 150,
    effect: {
      baseMagnitude: 0,
      magnitudePerLevel: 0,
      customHandler: 'shadow_step',
    },
    useVerb: 'shadow step',
    useMessage: 'You melt into the shadows and reappear behind $T!',
  },
  {
    id: 'thief:assassinate',
    name: 'Assassinate',
    description: 'A lethal strike that deals devastating damage to unsuspecting targets.',
    type: 'combat',
    target: 'single',
    guild: 'thief',
    guildLevelRequired: 20,
    manaCost: 60,
    cooldown: 60000,
    maxLevel: 100,
    learnCost: 10000,
    advanceCostPerLevel: 300,
    prerequisites: ['thief:backstab'],
    effect: {
      baseMagnitude: 100,
      magnitudePerLevel: 3.0,
      damageType: 'piercing',
    },
    useVerb: 'assassinate',
    useMessage: 'You strike with deadly precision, assassinating $T!',
  },
];

// ==================== CLERIC GUILD ====================

export const CLERIC_GUILD: GuildDefinition = {
  id: 'cleric',
  name: 'Cleric Guild',
  description: 'The Cleric Guild serves the divine, training healers and holy warriors in the arts of restoration and divine wrath. Clerics excel at healing allies and smiting the undead.',
  primaryStats: ['wisdom', 'charisma'],
  statRequirements: { wisdom: 12, charisma: 8 },
  skillTree: [
    { guildLevel: 1, skills: ['cleric:heal', 'cleric:divine_grace'] },
    { guildLevel: 3, skills: ['cleric:bless'] },
    { guildLevel: 5, skills: ['cleric:cure_poison'] },
    { guildLevel: 7, skills: ['cleric:turn_undead'] },
    { guildLevel: 10, skills: ['cleric:group_heal'] },
    { guildLevel: 13, skills: ['cleric:divine_shield'] },
    { guildLevel: 16, skills: ['cleric:holy_smite'] },
    { guildLevel: 20, skills: ['cleric:resurrection'] },
  ],
  channelColor: 'yellow',
  motto: 'By light, we heal. By faith, we conquer.',
  guildHallPath: '/areas/guilds/cleric/guild_hall',
};

export const CLERIC_SKILLS: SkillDefinition[] = [
  {
    id: 'cleric:heal',
    name: 'Heal',
    description: 'Restore health to a target.',
    type: 'combat',
    target: 'single',
    guild: 'cleric',
    guildLevelRequired: 1,
    manaCost: 20,
    cooldown: 4000,
    maxLevel: 100,
    learnCost: 50,
    advanceCostPerLevel: 25,
    effect: {
      baseMagnitude: 30,
      magnitudePerLevel: 1.0,
      healing: true,
    },
    useVerb: 'cast',
    useMessage: 'You channel divine energy to heal $T!',
  },
  {
    id: 'cleric:divine_grace',
    name: 'Divine Grace',
    description: 'Passive wisdom bonus from divine connection.',
    type: 'passive',
    target: 'none',
    guild: 'cleric',
    guildLevelRequired: 1,
    manaCost: 0,
    cooldown: 0,
    maxLevel: 50,
    learnCost: 100,
    advanceCostPerLevel: 50,
    effect: {
      baseMagnitude: 2,
      magnitudePerLevel: 0.5,
      statModifier: 'wisdom',
    },
  },
  {
    id: 'cleric:bless',
    name: 'Bless',
    description: 'Bless a target, increasing their accuracy.',
    type: 'buff',
    target: 'single',
    guild: 'cleric',
    guildLevelRequired: 3,
    manaCost: 15,
    cooldown: 30000,
    maxLevel: 50,
    learnCost: 200,
    advanceCostPerLevel: 40,
    effect: {
      baseMagnitude: 10,
      magnitudePerLevel: 0.5,
      combatStatModifier: 'toHit',
      duration: 300000,
    },
    useVerb: 'bless',
    useMessage: 'You bless $T with divine favor!',
  },
  {
    id: 'cleric:cure_poison',
    name: 'Cure Poison',
    description: 'Remove poison effects from a target.',
    type: 'utility',
    target: 'single',
    guild: 'cleric',
    guildLevelRequired: 5,
    manaCost: 25,
    cooldown: 10000,
    maxLevel: 50,
    learnCost: 500,
    advanceCostPerLevel: 60,
    effect: {
      baseMagnitude: 1,
      magnitudePerLevel: 0,
      customHandler: 'cure_poison',
    },
    useVerb: 'cure',
    useMessage: 'You channel purifying light into $T, cleansing the poison!',
  },
  {
    id: 'cleric:turn_undead',
    name: 'Turn Undead',
    description: 'Deal holy damage to undead creatures.',
    type: 'combat',
    target: 'single',
    guild: 'cleric',
    guildLevelRequired: 7,
    manaCost: 30,
    cooldown: 15000,
    maxLevel: 100,
    learnCost: 800,
    advanceCostPerLevel: 80,
    effect: {
      baseMagnitude: 40,
      magnitudePerLevel: 1.2,
      damageType: 'holy',
    },
    useVerb: 'raise your holy symbol at',
    useMessage: 'You raise your holy symbol at $T, unleashing divine wrath!',
  },
  {
    id: 'cleric:group_heal',
    name: 'Group Heal',
    description: 'Heal all allies in the room.',
    type: 'combat',
    target: 'room',
    guild: 'cleric',
    guildLevelRequired: 10,
    manaCost: 60,
    cooldown: 30000,
    maxLevel: 100,
    learnCost: 1500,
    advanceCostPerLevel: 100,
    effect: {
      baseMagnitude: 25,
      magnitudePerLevel: 0.8,
      healing: true,
    },
    useVerb: 'channel',
    useMessage: 'You channel a wave of healing energy through the room!',
  },
  {
    id: 'cleric:divine_shield',
    name: 'Divine Shield',
    description: 'Surround yourself with a shield of holy light.',
    type: 'buff',
    target: 'self',
    guild: 'cleric',
    guildLevelRequired: 13,
    manaCost: 40,
    cooldown: 90000,
    maxLevel: 50,
    learnCost: 2500,
    advanceCostPerLevel: 120,
    effect: {
      baseMagnitude: 30,
      magnitudePerLevel: 1.0,
      combatStatModifier: 'armorBonus',
      duration: 60000,
    },
    useVerb: 'invoke',
    useMessage: 'You invoke a divine shield of holy light around yourself!',
  },
  {
    id: 'cleric:holy_smite',
    name: 'Holy Smite',
    description: 'Call down holy fire upon your enemies.',
    type: 'combat',
    target: 'room',
    guild: 'cleric',
    guildLevelRequired: 16,
    manaCost: 70,
    cooldown: 45000,
    maxLevel: 100,
    learnCost: 5000,
    advanceCostPerLevel: 200,
    effect: {
      baseMagnitude: 50,
      magnitudePerLevel: 1.5,
      damageType: 'holy',
    },
    useVerb: 'call down',
    useMessage: 'You call down holy fire upon your enemies!',
  },
  {
    id: 'cleric:resurrection',
    name: 'Resurrection',
    description: 'Return a dead player to life.',
    type: 'utility',
    target: 'single',
    guild: 'cleric',
    guildLevelRequired: 20,
    manaCost: 100,
    cooldown: 600000,
    maxLevel: 20,
    learnCost: 10000,
    advanceCostPerLevel: 500,
    effect: {
      baseMagnitude: 1,
      magnitudePerLevel: 0,
      customHandler: 'resurrection',
    },
    useVerb: 'call upon the divine to resurrect',
    useMessage: 'You call upon the divine to resurrect $T from death!',
  },
];

// ==================== REGISTRATION HELPERS ====================

/**
 * Get all guild definitions.
 */
export function getAllGuildDefinitions(): GuildDefinition[] {
  return [FIGHTER_GUILD, MAGE_GUILD, THIEF_GUILD, CLERIC_GUILD];
}

/**
 * Get all skill definitions.
 */
export function getAllSkillDefinitions(): SkillDefinition[] {
  return [
    ...FIGHTER_SKILLS,
    ...MAGE_SKILLS,
    ...THIEF_SKILLS,
    ...CLERIC_SKILLS,
  ];
}

/**
 * Get skills for a specific guild.
 */
export function getSkillsForGuild(guildId: GuildId): SkillDefinition[] {
  switch (guildId) {
    case 'fighter':
      return FIGHTER_SKILLS;
    case 'mage':
      return MAGE_SKILLS;
    case 'thief':
      return THIEF_SKILLS;
    case 'cleric':
      return CLERIC_SKILLS;
    default:
      return [];
  }
}
