/**
 * Center of Town!
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.776Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Room } from '../../../lib/std.js';

export class Center extends Room {
  constructor() {
    super();
    this.shortDesc = 'Center of Town!';
    this.longDesc = `You stand in the heart of a bustling medieval town square. {dim}Cobblestones worn
smooth by countless feet spread out in all directions{/}, and a magnificent {cyan}stone
fountain{/} dominates the center, its {CYAN}crystal waters{/} catching the sunlight.

{yellow}Merchants{/} hawk their wares from colorful stalls lining the square's edges, their
voices mingling with the clatter of horse hooves and the chatter of townsfolk.
The aroma of {yellow}fresh bread{/} wafts from a nearby bakery, competing with the earthy
scent of the {red}blacksmith's forge{/}.

To the {green}north{/}, the imposing walls of the {bold}castle{/} rise above the rooftops. An old
{yellow}tavern{/} with a weathered sign creaks in the breeze to the {green}east{/}. The {green}western{/} road
leads toward the merchant district, while {green}southward{/} lies the town gates and the
wilderness beyond. A sturdy building to the {green}northeast{/} bears the sign of a crossed
sword and shield - the {cyan}training hall{/}. To the {green}southeast{/}, the solid stone walls of
the {yellow}Bank of Aldric{/} promise security for your hard-earned gold. A dim {red}pub{/} called
{red}The Rusty Blade{/} lies to the {green}southwest{/}, where mercenaries gather.

Around the square, guild halls beckon adventurers: the {red}Fighter Guild{/} arena
({green}fighter{/}), the {blue}Mage Guild{/} tower ({green}mage{/}), the {dim}Thief Guild{/} den ({green}thief{/}),
and the {yellow}Cleric Guild{/} temple ({green}cleric{/}).

A {magenta}town crier{/} stands near the fountain, occasionally announcing the day's news to
anyone who will listen.`;
    this.setMapCoordinates({ x: 2, y: 2, z: 0, area: '/areas/valdoria/aldric' });
    this.setTerrain('town');
    this.mapIcon = '*';
    this.setupRoom();
    // Preserved custom code
    // Preserved custom code
    // Map coordinates - center of town is the hub
  }

  private setupRoom(): void {
    // Exits
    this.addExit('west', '/areas/valdoria/aldric/room_4_4_0');
    this.addExit('north', '/areas/valdoria/aldric/room_5_3_0');
    this.addExit('east', '/areas/valdoria/aldric/room_6_4_0');
    this.addExit('south', '/areas/valdoria/aldric/room_5_5_0');
    this.addExit('fighter', '/areas/guilds/fighter/guild_hall');
    this.addExit('mage', '/areas/guilds/mage/guild_hall');
    this.addExit('thief', '/areas/guilds/thief/guild_hall');
    this.addExit('cleric', '/areas/guilds/cleric/guild_hall');

    // NPCs
    this.setNpcs(['/areas/valdoria/aldric/town_crier']);
  }

  // Preserved custom methods
  override async onCreate(): Promise<void> {
        await super.onCreate();
    
        // Spawn NPCs defined via setNpcs()
        await this.spawnMissingNpcs();
      }

  override async onEnter(obj: MudObject, from?: MudObject): Promise<void> {
        const receiver = obj as MudObject & { receive?: (msg: string) => void };
        if (typeof receiver.receive === 'function') {
          receiver.receive('\nYou emerge into the bustling town square.\n');
        }
    
        // Notify others
        this.broadcast(`${obj.shortDesc} arrives in the square.`, { exclude: [obj] });
      }

  override async onLeave(obj: MudObject, to?: MudObject): Promise<void> {
        this.broadcast(`${obj.shortDesc} leaves the square.`, { exclude: [obj] });
      }

  private async goCustomExit(direction: string): Promise<boolean> {
        // Find a connected player in the room
        const player = this.findPlayerInRoom();
        if (!player) return false;
    
        const living = player as MudObject & { moveDirection?: (dir: string) => Promise<boolean> };
        if (typeof living.moveDirection === 'function') {
          await living.moveDirection(direction);
          return true;
        }
        return false;
      }

  private cmdLook(args: string): boolean {
        const player = this.findPlayerInRoom();
        if (!player) return false;
    
        if (!args) {
          this.look(player);
          return true;
        }
    
        const target = args.toLowerCase();
        const receiver = player as MudObject & { receive?: (msg: string) => void };
    
        if (target === 'fountain' || target === 'water') {
          if (typeof receiver.receive === 'function') {
            receiver.receive(
              '\nThe fountain is carved from pale marble, depicting a heroic knight\n' +
              'slaying a fearsome dragon. Crystal-clear water arcs gracefully from\n' +
              'the dragon\'s mouth, splashing into the wide basin below. Copper coins\n' +
              'glint at the bottom, wishes cast by hopeful townsfolk.\n'
            );
          }
          return true;
        }
    
        if (target === 'merchants' || target === 'stalls' || target === 'market') {
          if (typeof receiver.receive === 'function') {
            receiver.receive(
              '\nColorful canvas awnings shade the merchant stalls. You see vendors\n' +
              'selling everything from fresh vegetables and salted meats to bolts of\n' +
              'cloth and simple tools. A few specialized traders offer more exotic\n' +
              'wares: potions, scrolls, and curious trinkets from distant lands.\n'
            );
          }
          return true;
        }
    
        if (target === 'crier' || target === 'town crier') {
          if (typeof receiver.receive === 'function') {
            receiver.receive(
              '\nThe town crier is a stout man in a faded blue coat, his voice\n' +
              'surprisingly powerful for his size. A brass bell hangs at his belt,\n' +
              'which he rings before each announcement. He notices your gaze and\n' +
              'gives you a friendly nod.\n'
            );
          }
          return true;
        }
    
        if (target === 'castle') {
          if (typeof receiver.receive === 'function') {
            receiver.receive(
              '\nThe castle towers above the town, its gray stone walls standing\n' +
              'sentinel for generations. Colorful banners flutter from the\n' +
              'battlements, and you can just make out the gleam of guards\' armor\n' +
              'on the ramparts. The road north leads to its imposing gates.\n'
            );
          }
          return true;
        }
    
        if (target === 'tavern' || target === 'sign') {
          if (typeof receiver.receive === 'function') {
            receiver.receive(
              '\nThe tavern\'s sign depicts a golden tankard overflowing with foam,\n' +
              'beneath which the words "The Foaming Flagon" are carved in bold\n' +
              'letters. Warm light spills from its windows, and the muffled sounds\n' +
              'of laughter and music hint at the merriment within.\n'
            );
          }
          return true;
        }
    
        if (target === 'training hall' || target === 'training' || target === 'hall') {
          if (typeof receiver.receive === 'function') {
            receiver.receive(
              '\nThe training hall is a sturdy stone building with a sign depicting\n' +
              'crossed swords over a shield. Through the open doors, you can see\n' +
              'practice dummies and racks of wooden training weapons. This is where\n' +
              'aspiring warriors come to hone their skills under expert instruction.\n'
            );
          }
          return true;
        }
    
        // Look at inventory or room contents
        for (const obj of this.inventory) {
          if (obj.id(target)) {
            if (typeof receiver.receive === 'function') {
              receiver.receive(`\n${obj.longDesc}\n`);
            }
            return true;
          }
        }
    
        if (typeof receiver.receive === 'function') {
          receiver.receive("\nYou don't see that here.\n");
        }
        return true;
      }

  private cmdListen(args: string): boolean {
        const player = this.findPlayerInRoom();
        if (!player) return false;
    
        const receiver = player as MudObject & { receive?: (msg: string) => void };
        if (typeof receiver.receive === 'function') {
          receiver.receive(
            '\nYou pause and listen to the symphony of town life:\n' +
            'The splash of the fountain, the cries of merchants advertising their\n' +
            'wares, the rhythmic clang of the blacksmith\'s hammer, children\n' +
            'laughing as they chase each other through the square, and beneath it\n' +
            'all, the gentle murmur of countless conversations.\n'
          );
        }
        return true;
      }

  private cmdDrink(args: string): boolean {
        const player = this.findPlayerInRoom();
        if (!player) return false;
    
        const target = args.toLowerCase();
        const receiver = player as MudObject & { receive?: (msg: string) => void };
    
        if (!target || target === 'water' || target === 'fountain') {
          if (typeof receiver.receive === 'function') {
            receiver.receive(
              '\nYou cup your hands in the fountain\'s cool water and drink deeply.\n' +
              'The water is fresh and pure, fed by mountain springs. You feel\n' +
              'refreshed and invigorated.\n'
            );
          }
          this.broadcast(`${player.shortDesc} drinks from the fountain.`, { exclude: [player] });
    
          // Could heal the player here
          const living = player as MudObject & { heal?: (amount: number) => void };
          if (typeof living.heal === 'function') {
            living.heal(2);
          }
          return true;
        }
    
        if (typeof receiver.receive === 'function') {
          receiver.receive("\nDrink what?\n");
        }
        return true;
      }

  private findPlayerInRoom(): MudObject | undefined {
        for (const obj of this.inventory) {
          const player = obj as MudObject & { isConnected?: () => boolean };
          if (typeof player.isConnected === 'function') {
            return obj;
          }
        }
        return this.inventory[0];
      }
}

export default Center;
