/**
 * food vendor
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.791Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Merchant } from '../../../lib/std.js';
import { Merchant } from '../../../std/merchant.js';

export class FoodVendor extends Merchant {
  constructor() {
    super();
    this.shortDesc = 'Marta the Food Vendor';
    this.longDesc = `Marta is a cheerful, round-faced woman with rosy cheeks and flour-dusted
hands. She wears a practical apron over a simple brown dress, and her
graying hair is tucked under a kerchief. Her stall is lined with baskets
of fresh bread, wrapped meats, and bundles of supplies for travelers.

A pile of firewood and pouches of tinder sit in one corner - she clearly
caters to adventurers who camp on the road.`;
    this.setLevel(5, 'normal');
    // Override auto-calculated health
    this.maxHealth = 60;
    this.health = 60;
    this.gender = 'female';
    this.chats = [
      { message: 'arranges some apples in a wicker basket.', type: 'emote' },
      { message: 'Fresh provisions for your journey!', type: 'say' },
      { message: 'wipes her hands on her apron.', type: 'emote' },
      { message: 'Best stew in Aldric, I promise you that!', type: 'say' },
      { message: 'wraps some bread in clean cloth.', type: 'emote' },
      { message: 'Got everything an adventurer needs - food, firewood, tinder!', type: 'say' },
    ];
    this.responses = [
      { pattern: 'hello|hi|greetings|hey', response: 'Welcome, ${speaker.name || \'traveler\'}! Looking for provisions?', type: 'say' },
      { pattern: 'shop|buy|sell|trade|wares|browse', response: 'I\'ve got food to fill your belly and supplies for camping. Just say \'shop\' to see what I have!', type: 'say' },
      { pattern: 'bread|loaf', response: 'Fresh bread, baked this morning! Nothing fancy, but it\'ll keep you going.', type: 'say' },
      { pattern: 'meat|cooked', response: 'The cooked meat is from the butcher next door - I season it with my special herbs!', type: 'say' },
      { pattern: 'stew', response: 'My hearty stew is legendary! Chunks of meat, fresh vegetables, and a secret blend of spices. It\'ll warm you right up and keep healing you for a while!', type: 'say' },
      { pattern: 'rations|travel', response: 'Travel rations - dried meat, hard cheese, and biscuits. Keeps well on the road!', type: 'say' },
      { pattern: 'firewood|wood|fire', response: 'Planning to make camp? You\'ll need three bundles of firewood and some tinder to start a campfire.', type: 'say' },
      { pattern: 'tinder|spark', response: 'Tinder\'s essential for starting fires. Dry moss, wood shavings, and such. One pouch is all you need.', type: 'say' },
      { pattern: 'campfire|camp|craft', response: 'To make a campfire, you\'ll need three firewood bundles and one tinder pouch. Use \'craft campfire\' when you have the materials!', type: 'say' },
      { pattern: 'heal|health|recover', response: 'Food\'s good for healing! Bread for a quick bite, meat for something heartier, or stew if you want the best - it\'ll keep healing you over time!', type: 'say' },
      { pattern: 'thank|thanks', response: 'smiles warmly. "Safe travels, dear!"', type: 'emote' },
    ];
    this.setMerchant({
      name: 'food vendor',
      shopName: 'Marta\\',
      shopDescription: 'Fresh food, travel supplies, and camping materials.',
      buyRate: 0.4,
      sellRate: 1,
      acceptedTypes: ['food', 'misc'],
      shopGold: 500,
      charismaEffect: 0.01,
    });
    // Shop inventory
    this.addStock('/std/consumables/bread', 'Loaf of Bread', 3, -1, 'food');
    this.addStock('/std/consumables/cooked_meat', 'Cooked Meat', 10, -1, 'food');
    this.addStock('/std/consumables/hearty_stew', 'Hearty Stew', 25, 10, 'food');
    this.addStock('/std/consumables/travel_rations', 'Travel Rations', 5, -1, 'food');
    this.addStock('/std/consumables/apple', 'Apple', 1, -1, 'food');
    this.addStock('/std/materials/firewood', 'Firewood Bundle', 2, -1, 'misc');
    this.addStock('/std/materials/tinder', 'Tinder Pouch', 1, -1, 'misc');
    this.addStock('/std/consumables/bread', 'Loaf of Bread', 3, -1, 'food');
    this.addStock('/std/consumables/cooked_meat', 'Cooked Meat', 10, -1, 'food');
    this.addStock('/std/consumables/hearty_stew', 'Hearty Stew', 25, 10, 'food');
    this.addStock('/std/consumables/travel_rations', 'Travel Rations', 5, -1, 'food');
    this.addStock('/std/consumables/apple', 'Apple', 1, -1, 'food');
    this.addStock('/std/materials/firewood', 'Firewood Bundle', 2, -1, 'misc');
    this.addStock('/std/materials/tinder', 'Tinder Pouch', 1, -1, 'misc');

    // Preserved custom code
    // Override auto-calculated health
    // Preserved custom code
    // Configure the merchant
    // Set NPC properties
    // Use auto-balance for level 5 normal (civilian vendor)
    // Override health - she's a civilian
    // Stock the shop
    this.setupStock();
    this.setupChats();
    this.setupResponses();
  }

  // Preserved custom methods
  private setupStock(): void {
        // Food items (path, name, price, quantity, category)
        this.addStock('/std/consumables/bread', 'Loaf of Bread', 3, -1, 'food');
        this.addStock('/std/consumables/cooked_meat', 'Cooked Meat', 10, -1, 'food');
        this.addStock('/std/consumables/hearty_stew', 'Hearty Stew', 25, 10, 'food');
        this.addStock('/std/consumables/travel_rations', 'Travel Rations', 5, -1, 'food');
        this.addStock('/std/consumables/apple', 'Apple', 1, -1, 'food');
    
        // Crafting materials
        this.addStock('/std/materials/firewood', 'Firewood Bundle', 2, -1, 'misc');
        this.addStock('/std/materials/tinder', 'Tinder Pouch', 1, -1, 'misc');
      }

  private setupChats(): void {
        this.addChat('arranges some apples in a wicker basket.', 'emote');
        this.addChat('Fresh provisions for your journey!', 'say');
        this.addChat('wipes her hands on her apron.', 'emote');
        this.addChat('Best stew in Aldric, I promise you that!', 'say');
        this.addChat('wraps some bread in clean cloth.', 'emote');
        this.addChat("Got everything an adventurer needs - food, firewood, tinder!", 'say');
      }

  private setupResponses(): void {
        this.addResponse(
          /hello|hi|greetings|hey/i,
          (speaker) =>
            `Welcome, ${speaker.name || 'traveler'}! Looking for provisions?`,
          'say'
        );
    
        this.addResponse(
          /shop|buy|sell|trade|wares|browse/i,
          "I've got food to fill your belly and supplies for camping. Just say 'shop' to see what I have!",
          'say'
        );
    
        this.addResponse(
          /bread|loaf/i,
          "Fresh bread, baked this morning! Nothing fancy, but it'll keep you going.",
          'say'
        );
    
        this.addResponse(
          /meat|cooked/i,
          "The cooked meat is from the butcher next door - I season it with my special herbs!",
          'say'
        );
    
        this.addResponse(
          /stew/i,
          "My hearty stew is legendary! Chunks of meat, fresh vegetables, and a secret blend of spices. It'll warm you right up and keep healing you for a while!",
          'say'
        );
    
        this.addResponse(
          /rations|travel/i,
          "Travel rations - dried meat, hard cheese, and biscuits. Keeps well on the road!",
          'say'
        );
    
        this.addResponse(
          /firewood|wood|fire/i,
          "Planning to make camp? You'll need three bundles of firewood and some tinder to start a campfire.",
          'say'
        );
    
        this.addResponse(
          /tinder|spark/i,
          "Tinder's essential for starting fires. Dry moss, wood shavings, and such. One pouch is all you need.",
          'say'
        );
    
        this.addResponse(
          /campfire|camp|craft/i,
          "To make a campfire, you'll need three firewood bundles and one tinder pouch. Use 'craft campfire' when you have the materials!",
          'say'
        );
    
        this.addResponse(
          /heal|health|recover/i,
          "Food's good for healing! Bread for a quick bite, meat for something heartier, or stew if you want the best - it'll keep healing you over time!",
          'say'
        );
    
        this.addResponse(
          /thank|thanks/i,
          'smiles warmly. "Safe travels, dear!"',
          'emote'
        );
      }

  override async onCreate(): Promise<void> {
        await super.onCreate();
    
        if (typeof efuns !== 'undefined' && efuns.setHeartbeat) {
          efuns.setHeartbeat(this, true);
        }
      }

  override async onEnter(who: Living, from?: Room): Promise<void> {
        const random = Math.random() * 100;
        if (random < 30) {
          setTimeout(() => {
            this.say('Welcome! Looking for food or supplies?');
          }, 1000);
        }
      }
}

export default FoodVendor;
