/**
 * master vorn
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.792Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Trainer } from '../../../lib/std.js';
import { Trainer } from '../../../std/trainer.js';

export class MasterVorn extends Trainer {
  constructor() {
    super();
    this.shortDesc = 'Master Vorn, the combat trainer';
    this.longDesc = `Master Vorn is a grizzled veteran with more scars than hair remaining
on his weathered head. His arms are thick with muscle despite his age,
and his eyes hold the sharp awareness of someone who has survived
countless battles. He wears simple training clothes - a loose tunic
and leather pants - but carries himself with the quiet confidence of
a master warrior. A wooden training sword rests against the wall
beside him, well-worn from years of instruction.`;
    this.setLevel(25, 'normal');
    // Override auto-calculated health
    this.maxHealth = 200;
    this.health = 200;
    this.gender = 'male';
    this.chatChance = 10;
    this.chats = [
      { message: 'stretches his arms and cracks his knuckles.', type: 'emote' },
      { message: 'Practice makes perfect. Never stop training.', type: 'say' },
      { message: 'examines a training dummy critically.', type: 'emote' },
      { message: 'The body and mind must grow together.', type: 'say' },
      { message: 'picks up a wooden sword and swings it experimentally.', type: 'emote' },
      { message: 'Every scar tells a story. Learn from each one.', type: 'say' },
    ];
    this.responses = [
      { pattern: 'hello|hi|greetings|hey', response: 'Welcome, ${speaker.name || \'adventurer\'}. Ready to work on your skills?', type: 'say' },
      { pattern: 'train|learn|teach|stronger|level', response: 'Type \'train\' to see what I can help you with. I can improve your combat abilities and help you reach new heights of power.', type: 'say' },
      { pattern: 'thank|thanks', response: 'nods approvingly.', type: 'emote' },
      { pattern: 'who are you|your name|yourself', response: 'I am Master Vorn. I\'ve spent forty years mastering the arts of combat, and now I pass that knowledge to the next generation.', type: 'say' },
      { pattern: 'experience|xp|cost', response: 'Training requires experience points. The more skilled you become, the harder it is to improve further. Type \'train\' to see the costs.', type: 'say' },
      { pattern: 'stat|strength|dex|int|wis|con|cha|luck', response: 'I can train all of your core attributes - strength, dexterity, constitution, intelligence, wisdom, charisma, and even luck. Each makes you stronger in different ways.', type: 'say' },
    ];
    this.setTrainerConfig({
      canTrainLevel: true,
      costMultiplier: 1,
      greeting: 'Ah, another soul seeking to grow stronger! Let',
    });

    this.setupChats();
    this.setupResponses();
  }

  // Preserved custom methods
  private setupChats(): void {
        this.addChat('stretches his arms and cracks his knuckles.', 'emote');
        this.addChat('Practice makes perfect. Never stop training.', 'say');
        this.addChat('examines a training dummy critically.', 'emote');
        this.addChat('The body and mind must grow together.', 'say');
        this.addChat('picks up a wooden sword and swings it experimentally.', 'emote');
        this.addChat('Every scar tells a story. Learn from each one.', 'say');
        this.addChat("I've trained warriors who went on to become legends.", 'say');
      }

  private setupResponses(): void {
        // Respond to greetings
        this.addResponse(
          /hello|hi|greetings|hey/i,
          (speaker) => `Welcome, ${speaker.name || 'adventurer'}. Ready to work on your skills?`,
          'say'
        );
    
        // Respond to training questions
        this.addResponse(
          /train|learn|teach|stronger|level/i,
          "Type 'train' to see what I can help you with. I can improve your combat abilities and help you reach new heights of power.",
          'say'
        );
    
        // Respond to thanks
        this.addResponse(
          /thank|thanks/i,
          'nods approvingly.',
          'emote'
        );
    
        // Respond to questions about himself
        this.addResponse(
          /who are you|your name|yourself/i,
          "I am Master Vorn. I've spent forty years mastering the arts of combat, and now I pass that knowledge to the next generation.",
          'say'
        );
    
        // Respond to questions about experience
        this.addResponse(
          /experience|xp|cost/i,
          "Training requires experience points. The more skilled you become, the harder it is to improve further. Type 'train' to see the costs.",
          'say'
        );
    
        // Respond to questions about stats
        this.addResponse(
          /stat|strength|dex|int|wis|con|cha|luck/i,
          "I can train all of your core attributes - strength, dexterity, constitution, intelligence, wisdom, charisma, and even luck. Each makes you stronger in different ways.",
          'say'
        );
      }

  override async onCreate(): Promise<void> {
        await super.onCreate();
    
        if (typeof efuns !== 'undefined' && efuns.setHeartbeat) {
          efuns.setHeartbeat(this, true);
        }
      }

  override async onEnter(who: Living, from?: Room): Promise<void> {
        const random = Math.random() * 100;
        if (random < 40) {
          setTimeout(() => {
            const name = who.name || 'adventurer';
            this.say(`Ah, ${name}. Come to train, have you?`);
          }, 1000);
        }
      }
}

export default MasterVorn;
