/**
 * Merchant Aldwin
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.793Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { NPC } from '../../../lib/std.js';

export class Merchant extends NPC {
  constructor() {
    super();
    this.name = 'Merchant Aldwin';
    this.shortDesc = 'Merchant Aldwin';
    this.longDesc = `Merchant Aldwin is a well-dressed man in his middle years, though his
fine traveling clothes are dusty and disheveled. His usually jovial
face is creased with worry, and he paces anxiously near his empty
cart. The cart's broken wheel tells the story of a recent misfortune.

He keeps glancing toward the south road, muttering about bandits
and lost profits. Several other merchants cast sympathetic looks
his way, but business is business.`;
    this.setLevel(5, 'normal');
    // Override auto-calculated health
    this.maxHealth = 60;
    this.health = 60;
    this.gender = 'male';
    this.chatChance = 10;
    this.chats = [
      { message: 'kicks at the broken wheel of his cart in frustration.', type: 'emote' },
      { message: 'paces back and forth, wringing his hands.', type: 'emote' },
      { message: 'peers anxiously toward the south road.', type: 'emote' },
      { message: 'Three crates of valuable goods... just taken!', type: 'say' },
    ];
    this.responses = [
      { pattern: 'hello|hi|greetings|hey', response: 'Oh, ${speaker.name || \'traveler\'}... forgive me, I\'m not in the best of spirits today.', type: 'say' },
      { pattern: 'bandit|supplies|crate|stolen|help|problem', response: 'Bandits attacked my caravan on the south road yesterday! They took three crates of valuable supplies meant for the shops here. If someone could recover them before they\'re sold on the black market, I\'d pay handsomely!', type: 'say' },
      { pattern: 'cart|wheel|broken', response: 'looks at his cart sadly. "The bandits broke the wheel when they ambushed us. At least they didn\'t take the cart itself... small mercies."', type: 'emote' },
      { pattern: 'reward|pay|gold', response: 'I\'ll pay fifty gold coins for the safe return of my supplies, plus the eternal gratitude of the Merchant\'s Guild. Those crates are worth far more than that!', type: 'say' },
      { pattern: 'thank|thanks', response: 'nods gratefully.', type: 'emote' },
      { pattern: 'quest', response: 'clasps his hands together pleadingly. "Please, if you could recover my stolen supplies, type \'quest accept\' and I\'ll make it worth your while!"', type: 'emote' },
    ];
    this.setQuestsOffered(['aldric:lost_supplies']);
    this.setQuestsTurnedIn(['aldric:lost_supplies']);

    // Preserved custom code
    // Override auto-calculated health
    // Preserved custom code
    // Use auto-balance for level 5 normal (civilian)
    // Override health - he's a civilian, not a fighter
    // Quest giver configuration
    this.setupChats();
    this.setupResponses();
  }

  // Preserved custom methods
  private setupChats(): void {
        this.addChat('kicks at the broken wheel of his cart in frustration.', 'emote');
        this.addChat('Those cursed bandits! A season\'s worth of goods, gone!', 'say');
        this.addChat('paces back and forth, wringing his hands.', 'emote');
        this.addChat('The guild will have my head if I don\'t recover those supplies.', 'say');
        this.addChat('peers anxiously toward the south road.', 'emote');
        this.addChat('Three crates of valuable goods... just taken!', 'say');
      }

  private setupResponses(): void {
        this.addResponse(
          /hello|hi|greetings|hey/i,
          (speaker) => `Oh, ${speaker.name || 'traveler'}... forgive me, I'm not in the best of spirits today.`,
          'say'
        );
    
        this.addResponse(
          /bandit|supplies|crate|stolen|help|problem/i,
          "Bandits attacked my caravan on the south road yesterday! They took three crates of valuable supplies meant for the shops here. If someone could recover them before they're sold on the black market, I'd pay handsomely!",
          'say'
        );
    
        this.addResponse(
          /cart|wheel|broken/i,
          "looks at his cart sadly. \"The bandits broke the wheel when they ambushed us. At least they didn't take the cart itself... small mercies.\"",
          'emote'
        );
    
        this.addResponse(
          /reward|pay|gold/i,
          "I'll pay fifty gold coins for the safe return of my supplies, plus the eternal gratitude of the Merchant's Guild. Those crates are worth far more than that!",
          'say'
        );
    
        this.addResponse(
          /thank|thanks/i,
          'nods gratefully.',
          'emote'
        );
    
        this.addResponse(
          /quest/i,
          "clasps his hands together pleadingly. \"Please, if you could recover my stolen supplies, type 'quest accept' and I'll make it worth your while!\"",
          'emote'
        );
      }

  override async onCreate(): Promise<void> {
        await super.onCreate();
    
        if (typeof efuns !== 'undefined' && efuns.setHeartbeat) {
          efuns.setHeartbeat(this, true);
        }
      }

  override async onEnter(who: Living, from?: Room): Promise<void> {
        const random = Math.random() * 100;
        if (random < 30) {
          setTimeout(() => {
            this.say("Excuse me! You look capable - might I have a word about a pressing matter?");
          }, 1500);
        }
      }
}

export default Merchant;
