/**
 * pet keeper
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.794Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { PetMerchant } from '../../../lib/std.js';
import { PetMerchant } from '../../../std/pet-merchant.js';
import { getPetDaemon } from '../../../daemons/pet.js';

export class PetKeeper extends PetMerchant {
  constructor() {
    super();
    this.shortDesc = 'pet keeper';
    this.longDesc = ``;
    this.setLevel(1, 'normal');
    this.chats = [
      { message: 'pets a nearby puppy, causing it to wag its tail furiously.', type: 'emote' },
      { message: 'fills water dishes for the animals.', type: 'emote' },
      { message: 'hums a cheerful tune while brushing one of the horses.', type: 'emote' },
      { message: 'adjusts some hay bales in the stable area.', type: 'emote' },
    ];
    this.setPetMerchant({
      name: 'pet keeper',
      shopName: 'Whiskers & Hooves Pet Emporium',
      shopDescription: 'Quality companions for adventurers of all kinds!',
    });
  }
}

export default PetKeeper;
