/**
 * Whiskers & Hooves Pet Emporium - Pet Keeper
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.794Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { PetMerchant } from '../../../std/pet-merchant.js';
import { petDogTemplate } from './items/pet_dog.js';
import { petCatTemplate } from './items/pet_cat.js';
import { petMuleTemplate } from './items/pet_mule.js';
import { petHorseTemplate } from './items/pet_horse.js';
import { petParrotTemplate } from './items/pet_parrot.js';

export class PetKeeper extends PetMerchant {
  constructor() {
    super();
    this.name = 'Mira';
    this.shortDesc = 'Mira the pet keeper';
    this.longDesc = `Mira is a cheerful young woman with hay in her auburn hair and a
warm smile that never fades. She wears simple work clothes covered
in animal fur and the occasional feather. Various small creatures
seem to gravitate toward her, and there's always at least one
puppy trailing at her heels.`;
    this.setLevel(5, 'normal');
    this.gender = 'female';

    this.setPetMerchant({
      name: 'Mira',
      shopName: 'Whiskers & Hooves Pet Emporium',
      shopDescription: 'Quality companions for adventurers of all kinds!',
    });

    this.setupStock();
    this.setupChats();
    this.setupResponses();
  }

  private setupStock(): void {
    this.addPetStock('dog', petDogTemplate, 100, 'A loyal canine companion. Small but faithful!');
    this.addPetStock('cat', petCatTemplate, 75, 'An independent feline friend. Catches mice for free!');
    this.addPetStock('mule', petMuleTemplate, 500, 'A reliable beast of burden. Can carry a fortune!');
    this.addPetStock('horse', petHorseTemplate, 800, 'A noble steed. Swift and strong!');
    this.addPetStock('parrot', petParrotTemplate, 150, 'A talkative companion. Might repeat secrets!');
  }

  private setupChats(): void {
    this.addChat('pets a nearby puppy, causing it to wag its tail furiously.', 'emote');
    this.addChat('fills water dishes for the animals.', 'emote');
    this.addChat('hums a cheerful tune while brushing one of the horses.', 'emote');
    this.addChat('adjusts some hay bales in the stable area.', 'emote');
    this.addChat('Every pet here is well-cared for and ready for adventure!', 'say');
    this.addChat('coos softly at a colorful parrot.', 'emote');
  }

  private setupResponses(): void {
    this.addResponse(
      /hello|hi|greetings|hey/i,
      (speaker) =>
        `Welcome to Whiskers & Hooves, ${speaker.name || 'friend'}! Looking for a loyal companion?`,
      'say'
    );

    this.addResponse(
      /pet|pets|buy|shop|list|browse/i,
      "I have dogs, cats, mules, horses, and even a parrot! Say 'list' to see what's available, or 'buy <pet>' to make a new friend!",
      'say'
    );

    this.addResponse(
      /dog/i,
      "Dogs are wonderful companions! Loyal and eager to please. They can carry a few items too.",
      'say'
    );

    this.addResponse(
      /cat/i,
      "Cats are independent but affectionate. They're small but they keep the mice away!",
      'say'
    );

    this.addResponse(
      /mule/i,
      "Mules are the best pack animals around. Strong and patient - perfect for long journeys.",
      'say'
    );

    this.addResponse(
      /horse/i,
      "Horses are noble creatures. Fast and beautiful, with room for your supplies.",
      'say'
    );

    this.addResponse(
      /parrot/i,
      "smiles at the parrot. 'This colorful fellow loves to talk. Just be careful what you say around him!'",
      'emote'
    );

    this.addResponse(
      /thank|thanks/i,
      'beams happily. "Take good care of your new friend!"',
      'emote'
    );
  }

  override async onCreate(): Promise<void> {
    await super.onCreate();

    if (typeof efuns !== 'undefined' && efuns.setHeartbeat) {
      efuns.setHeartbeat(this, true);
    }
  }
}

export default PetKeeper;
