/**
 * a cobblestone plaza before the castle
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.783Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Room } from '../../../lib/std.js';

export class Room530 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a cobblestone plaza before the castle';
    this.longDesc = `You stand in a wide cobblestone plaza that stretches between the imposing castle gates to the north and the bustling heart of Aldric to the south. Ancient stone benches line the edges of the square, worn smooth by countless citizens who have waited here for audiences with the nobility. The air carries the mingled scents of fresh bread from the town center and the metallic tang of armored guards patrolling the castle walls. Weathered banners bearing Aldric's coat of arms flutter from tall poles, their fabric dancing in Moradin's eternal winds.`;
    this.setMapCoordinates({ x: 2, y: 1, z: 0, area: '/areas/valdoria/aldric' });
    this.setTerrain('town');
    this.setupRoom();  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/aldric/castle');
    this.addExit('south', '/areas/valdoria/aldric/center');
    this.addExit('west', '/areas/guilds/fighter/guild_hall');
    this.addExit('east', '/areas/guilds/mage/guild_hall');

  }
}

export default Room530;
