/**
 * a narrow alley between stone buildings
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.782Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Room } from '../../../lib/std.js';

export class Room440 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a narrow alley between stone buildings';
    this.longDesc = `You find yourself in a narrow cobblestone alley that winds between tall stone buildings, their weathered facades bearing the patina of countless seasons. Wooden shutters hang slightly ajar from upper windows, and you catch glimpses of warm lamplight flickering within. The air carries the mingled scents of baking bread from nearby shops and the faint magical essence that seems to permeate all of Aldric. Moss creeps along the base of the ancient stonework, speaking to the town's enduring history.`;
    this.setMapCoordinates({ x: 1, y: 2, z: 0, area: '/areas/valdoria/aldric' });
    this.setTerrain('town');
    this.setupRoom();  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/aldric/forge');
    this.addExit('south', '/areas/valdoria/aldric/pet_store');
    this.addExit('east', '/areas/valdoria/aldric/center');
    this.addExit('west', '/areas/valdoria/aldric/room_3_4_0');

  }
}

export default Room440;
