/**
 * A bustling cobblestone crossroads
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.784Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Room } from '../../../lib/std.js';

export class Room640 extends Room {
  constructor() {
    super();
    this.shortDesc = 'A bustling cobblestone crossroads';
    this.longDesc = `You stand at a busy intersection where four cobblestone streets converge in the heart of Aldric. Merchants hurry past carrying bundles of goods while townsfolk pause to chat beneath the flickering light of wrought-iron lampposts. The air carries the mingled scents of fresh bread from nearby bakeries and the earthy smell of horses from the training grounds to the north. Weathered stone buildings line each street, their windows glowing warmly with the promise of shelter and commerce.`;
    this.setMapCoordinates({ x: 3, y: 2, z: 0, area: '/areas/valdoria/aldric' });
    this.setTerrain('town');
    this.setupRoom();  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/aldric/training_hall');
    this.addExit('south', '/areas/valdoria/aldric/market');
    this.addExit('west', '/areas/valdoria/aldric/center');
    this.addExit('east', '/areas/valdoria/aldric/room_7_4_0');

  }
}

export default Room640;
