/**
 * A bustling merchant quarter crossroads
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.783Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Room } from '../../../lib/std.js';

export class Room550 extends Room {
  constructor() {
    super();
    this.shortDesc = 'A bustling merchant quarter crossroads';
    this.longDesc = `You stand at the heart of Aldric's merchant quarter, where cobblestone streets converge beneath colorful canvas awnings stretched between timber-framed shops. The air hums with the chatter of traders hawking their wares, while the mingled scents of exotic spices, leather goods, and fresh bread drift from the nearby stalls. Elven artisans display intricate silverwork alongside human blacksmiths' sturdy tools, their voices weaving together in the ancient dance of commerce that has thrived here since Moradin first breathed life into the world.`;
    this.setMapCoordinates({ x: 2, y: 3, z: 0, area: '/areas/valdoria/aldric' });
    this.setTerrain('town');
    this.setupRoom();  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/aldric/center');
    this.addExit('south', '/areas/valdoria/aldric/gates');

  }
}

export default Room550;
