/**
 * a bustling cobblestone square
 *
 * Generated by Area Builder on 2026-01-25T15:37:49.214Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Room } from '../../../lib/std.js';

export class Room340 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a bustling cobblestone square';
    this.longDesc = `You stand in a well-worn cobblestone square at the heart of Aldric, where merchants and townsfolk hurry about their daily business. The mingled scents of leather from the nearby tannery and ale from the tavern create a distinctly urban aroma. Weathered wooden signs creak gently in the breeze, directing travelers to the various establishments that line this central thoroughfare.`;
    this.setMapCoordinates({ x: 0, y: 2, z: 0, area: '/areas/valdoria/aldric' });
    this.setTerrain('town');
    this.setupRoom();  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/aldric/tannery');
    this.addExit('south', '/areas/valdoria/aldric/pub');
    this.addExit('east', '/areas/valdoria/aldric/room_4_4_0');
    this.addExit('west', '/areas/valdoria/west_road/room_19_3_0');

  }
}

export default Room340;
