/**
 * A quiet residential street corner
 *
 * Generated by Area Builder on 2026-01-25T15:37:49.218Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Room } from '../../../lib/std.js';

export class Room740 extends Room {
  constructor() {
    super();
    this.shortDesc = 'A quiet residential street corner';
    this.longDesc = `You stand at the intersection of two narrow cobblestone streets lined with modest timber-framed houses. Wisps of smoke curl from stone chimneys while the warm glow of hearth fires flickers behind diamond-paned windows. The mingled aromas of freshly baked bread from the south and ale from the north drift on the evening breeze, creating a homely atmosphere that speaks of Aldric's simple comforts.`;
    this.setMapCoordinates({ x: 4, y: 2, z: 0, area: '/areas/valdoria/aldric' });
    this.setTerrain('town');
    this.setupRoom();  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/aldric/tavern');
    this.addExit('south', '/areas/valdoria/aldric/bakery');
    this.addExit('west', '/areas/valdoria/aldric/room_6_4_0');

  }
}

export default Room740;
