/**
 * town crier
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.795Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { NPC } from '../../../lib/std.js';

export class TownCrier extends NPC {
  constructor() {
    super();
    this.name = 'town crier';
    this.shortDesc = 'the town crier';
    this.longDesc = `The town crier is a stout man in a faded blue coat with brass buttons.
His voice is surprisingly powerful for his size, honed by years of
bellowing announcements across the busy square. A polished brass bell
hangs at his belt, which he rings before each proclamation. His face
is weathered but friendly, with keen eyes that miss little of the
comings and goings in the square. He carries a rolled parchment
tucked under one arm - no doubt containing the latest decrees and
news from the castle.`;
    this.setLevel(3, 'normal');
    // Override auto-calculated health
    this.maxHealth = 50;
    this.health = 50;
    this.gender = 'male';
    this.chatChance = 15;
    this.setQuestsOffered(['aldric:urgent_message', 'aldric:meet_guildmasters']);
    this.setQuestsTurnedIn(['aldric:urgent_message', 'aldric:meet_guildmasters']);
    this.setLookSound('npcs/town-crier.mp3');

    // Preserved custom code
    // Override auto-calculated health
    // Preserved custom code
    // Override auto-calculated health
  }
}

export default TownCrier;
