/**
 * Training Hall
 *
 * Generated by Area Builder on 2026-01-25T15:43:48.787Z
 * Area: Town of Aldric (valdoria:aldric)
 */

import { Room } from '../../../lib/std.js';

export class TrainingHall extends Room {
  constructor() {
    super();
    this.shortDesc = 'Training Hall';
    this.longDesc = `This spacious hall echoes with the sounds of training - the thud
of practice weapons against padded dummies, the scuff of boots on
the worn wooden floor. Racks of training equipment line the walls:
wooden swords, padded shields, and various weighted implements for
building strength. The floor shows the wear of countless sessions,
with smooth patches where feet have pivoted and struck for decades.
High windows let in diffused light, and the air carries the faint
scent of leather and honest sweat.

A chalk board near the entrance displays training schedules and
motivational quotes from famous warriors of old. Near the equipment
racks, a hand-painted sign reads: {yellow}"FREE GEAR FOR NEW ADVENTURERS!"{/}

The town center lies to the {green}southwest{/}.`;
    this.setMapCoordinates({ x: 3, y: 1, z: 0, area: '/areas/valdoria/aldric' });
    this.setTerrain('town');
    this.mapIcon = 'H';
    this.setupRoom();
    // Preserved custom code
    // Preserved custom code
    // Map coordinates - northeast of center
    // Set NPCs that belong to this room - they'll respawn on reset if missing
    // Add some items for flavor
    this.addId('training hall');
    this.addId('hall');
  }

  private setupRoom(): void {
    // Exits
    this.addExit('south', '/areas/valdoria/aldric/room_6_4_0');

    // NPCs
    this.setNpcs(['/areas/valdoria/aldric/master_vorn', '/areas/valdoria/aldric/newbie_armourer']);
  }

  // Preserved custom methods
  override async onCreate(): Promise<void> {
        await super.onCreate();
    
        // Spawn NPCs defined via setNpcs()
        await this.spawnMissingNpcs();
      }
}

export default TrainingHall;
