/**
 * Battleworn Sword
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.099Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Weapon } from '../../../lib/std.js';

export class BattlewornSword extends Weapon {
  constructor() {
    super();
    this.shortDesc = 'a battleworn sword';
    this.longDesc = `This weathered blade bears the scars of countless conflicts, its steel dulled by time and neglect. Deep nicks mar the edge while rust creeps along the fuller, suggesting it once belonged to a traveler who met an unfortunate end on these dusty roads. Despite its poor condition, the sword's balance remains true, hinting at the skilled craftsmanship that forged it in better days.`;
    this.weight = 1;
    this.value = 0;
    this.minDamage = 1;
    this.maxDamage = 3;
    this.damageType = 'slashing';
    this.handedness = 'one_handed';
  }
}

export default BattlewornSword;
