/**
 * Brother Mace, a traveler heading west.
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.098Z
 * Area: The Western Road (valdoria:west_road)
 */

import { NPC } from '../../../lib/std.js';

export class BrotherMace extends NPC {
  constructor() {
    super();
    this.name = 'Brother Mace, a traveler heading west.';
    this.shortDesc = 'a weathered monk in simple brown robes';
    this.longDesc = `Brother Mace stands with the quiet confidence of one who has walked many roads in service to his faith. His sun-weathered face bears the lines of countless miles, while calloused hands grip a worn wooden staff that has clearly seen both travel and combat. Dust from the western road clings to his simple brown robes, and his keen eyes hold the steady gaze of a man accustomed to facing whatever dangers the wilderness might offer.`;
    this.setLevel(4, 'normal');
    this.gender = 'male';
    this.keywords = ['mace', 'traveler'];
    this.wandering = false;
    this.respawnTime = 0;
  }
}

export default BrotherMace;
