/**
 * Calla, the Veiled Woman. 
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.098Z
 * Area: The Western Road (valdoria:west_road)
 */

import { NPC } from '../../../lib/std.js';

export class Calla extends NPC {
  constructor() {
    super();
    this.name = 'Calla, the Veiled Woman. ';
    this.shortDesc = 'a mysterious woman shrouded in dark veils';
    this.longDesc = `Calla stands motionless beside the dusty road, her entire form wrapped in layers of midnight-black silk that flutter gently in the western breeze. Only her pale hands are visible beneath the veils, clasped serenely before her as she gazes toward the horizon with an otherworldly stillness. There is something ancient and knowing in her posture, as if she has been waiting here for travelers far longer than any mortal should.`;
    this.setLevel(25, 'normal');
    this.gender = 'female';
    this.keywords = ['calla', 'veiled woman', 'woman'];
    this.wandering = false;
    this.respawnTime = 0;
  }
}

export default Calla;
