/**
 * Garrett Ironwheel
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.096Z
 * Area: The Western Road (valdoria:west_road)
 */

import { NPC } from '../../../lib/std.js';

export class CaravanMaster extends NPC {
  constructor() {
    super();
    this.name = 'Garrett Ironwheel';
    this.shortDesc = 'a weathered human merchant with a sturdy wagon';
    this.longDesc = `Garrett Ironwheel stands beside a well-maintained wooden wagon, its iron-reinforced wheels gleaming despite the dust of countless miles. Their sun-weathered face bears the confident expression of someone who has traveled these roads for decades, while calloused hands rest easily on the wagon's side. A practical traveler's cloak hangs from broad shoulders, and their keen eyes constantly scan the horizon for both opportunity and danger.`;
    this.setLevel(15, 'normal');
    this.gender = 'male';
    this.keywords = ['garrett', 'master'];
    this.wandering = false;
    this.respawnTime = 0;
  }
}

export default CaravanMaster;
