/**
 * Holst, a grizzled caravan guard
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.096Z
 * Area: The Western Road (valdoria:west_road)
 */

import { NPC } from '../../../lib/std.js';

export class CaravanGuard extends NPC {
  constructor() {
    super();
    this.name = 'Holst, a grizzled caravan guard';
    this.shortDesc = 'a grizzled caravan guard with weathered hands';
    this.longDesc = `Holst stands with the practiced ease of someone who has spent decades protecting merchant wagons along dangerous roads. Their sun-beaten face bears the scars of countless skirmishes, while keen eyes constantly scan the horizon for signs of trouble. A well-maintained sword hangs at their hip, and their travel-worn leather armor speaks of many miles traversed under Moradin's watchful sky.`;
    this.level = 18;
    this.maxHealth = 50;
    this.health = 50;
    this.gender = 'male';
    this.keywords = ['holst', 'guard'];
    this.wandering = false;
    this.respawnTime = 0;
    this.setSpawnItems(['/areas/valdoria/west_road/battleworn_sword', '/areas/valdoria/west_road/dragonscale_armor', '/areas/valdoria/west_road/dragonscale_leggings', '/areas/valdoria/west_road/dragonscale_boots']);
  }
}

export default CaravanGuard;
