/**
 * Seren Vay, the Caravan Scout.
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.097Z
 * Area: The Western Road (valdoria:west_road)
 */

import { NPC } from '../../../lib/std.js';

export class CaravanScout extends NPC {
  constructor() {
    super();
    this.name = 'Seren Vay, the Caravan Scout.';
    this.shortDesc = 'a weathered half-elf with keen eyes and travel-worn gear';
    this.longDesc = `Seren Vay stands with the easy confidence of one who has spent countless seasons navigating treacherous roads and unpredictable weather. Their androgynous features bear the subtle pointed ears of elven heritage, while sun-darkened skin and calloused hands speak to years of hard travel under Moradin's open sky. A well-maintained crossbow rests across their back, and their sharp amber eyes constantly scan the horizon with the practiced vigilance of someone who knows that danger can emerge from any bend in the road.`;
    this.setLevel(12, 'normal');
    this.gender = 'female';
    this.keywords = ['seren', 'scout'];
    this.wandering = false;
    this.respawnTime = 0;
  }
}

export default CaravanScout;
