/**
 * Dragonscale Leggings
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.100Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Armor } from '../../../lib/std.js';

export class DragonscaleLeggings extends Armor {
  constructor() {
    super();
    this.shortDesc = 'a pair of weathered dragonscale leggings';
    this.longDesc = `These battle-worn leggings are crafted from overlapping scales of deep crimson and bronze, each one bearing the distinctive ridged texture of true dragonhide. Though dulled by countless miles of travel along dusty roads, the scales still shimmer faintly with an inner fire, and the leather bindings show the expert craftsmanship typical of Dragonborn armorers. Mud and grime from the Western Road clings to the lower portions, telling tales of long journeys and arduous travels.`;
    this.weight = 1;
    this.value = 0;
    this.armor = 10;
    this.slot = 'legs';
  }
}

export default DragonscaleLeggings;
