/**
 * Dragonscale Boots
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.100Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Armor } from '../../../lib/std.js';

export class DragonscaleBoots extends Armor {
  constructor() {
    super();
    this.shortDesc = 'a pair of iridescent dragonscale boots';
    this.longDesc = `These magnificent boots are crafted from overlapping scales that shimmer with an inner fire, each scale edged in gold and ranging from deep crimson to burnished copper. The sturdy leather interior is lined with soft silk, while the soles are reinforced with additional scale plating that would serve any traveler well on the rough dirt roads. Faint wisps of warmth seem to emanate from the scales, suggesting these boots once belonged to a Dragonborn of fire lineage.`;
    this.weight = 1;
    this.value = 0;
    this.armor = 10;
    this.slot = 'feet';
  }
}

export default DragonscaleBoots;
