/**
 * Dragonscale Armor
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.099Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Armor } from '../../../lib/std.js';

export class DragonscaleArmor extends Armor {
  constructor() {
    super();
    this.shortDesc = 'a suit of burnished dragonscale armor';
    this.longDesc = `This magnificent suit of armor has been crafted from overlapping scales of deep crimson and bronze, each one polished to a mirror sheen that catches the light with an inner fire. The scales have been carefully arranged in traditional Dragonborn fashion, following the natural contours of draconic hide to provide maximum protection while maintaining flexibility. Faint wisps of heat seem to emanate from the armor's surface, suggesting it was forged from the scales of a fire-breathing dragon and still retains some of that ancient elemental power.`;
    this.weight = 1;
    this.value = 0;
    this.armor = 10;
    this.slot = 'chest';
  }
}

export default DragonscaleArmor;
