/**
 * a grassy meadow beside the dirt road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.092Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1410 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a grassy meadow beside the dirt road';
    this.longDesc = `You stand in a sun-dappled meadow where wild grasses sway gently in the breeze that carries Moradin's breath across the land. The Western Road stretches alongside this peaceful expanse, its packed earth worn smooth by countless travelers seeking their fortunes. Wildflowers dot the emerald carpet beneath your feet, their sweet fragrance mingling with the earthy scent of the well-traveled path. In the distance, you can hear the faint whisper of wind through grass, as if the sleeping god's dreams still echo across this tranquil stretch of countryside.`;
    this.setMapCoordinates({ x: 14, y: 1, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('south', '/areas/valdoria/west_road/room_14_2_0');
    this.addExit('north', '/areas/valdoria/west_road/room_14_0_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_15_0_0');
    this.addExit('east', '/areas/valdoria/west_road/room_15_1_0');
    this.addExit('west', '/areas/valdoria/west_road/room_13_1_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_15_2_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_13_2_0');

  }
}

export default Room1410;
