/**
 * A grassy meadow beside the western road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.095Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1700 extends Room {
  constructor() {
    super();
    this.shortDesc = 'A grassy meadow beside the western road';
    this.longDesc = `You stand in a wide expanse of rolling grassland that stretches endlessly toward the horizon. The packed dirt of the Western Road cuts through the verdant meadow to your east, its well-worn surface marked by countless wagon wheels and travelers' boots. Wildflowers dot the grass in patches of blue and yellow, swaying gently in the breeze that carries the earthy scent of rich soil and growing things. The open sky above seems vast and limitless, broken only by the occasional wisp of cloud drifting lazily overhead.`;
    this.setMapCoordinates({ x: 17, y: 0, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('south', '/areas/valdoria/west_road/room_17_1_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_16_1_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_18_1_0');
    this.addExit('west', '/areas/valdoria/west_road/room_16_0_0');
    this.addExit('east', '/areas/valdoria/west_road/room_18_0_0');

  }
}

export default Room1700;
