/**
 * A weathered crossroads on the western road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.089Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1620 extends Room {
  constructor() {
    super();
    this.shortDesc = 'A weathered crossroads on the western road';
    this.longDesc = `You stand at a dusty crossroads where the main western road intersects with a smaller dirt path heading north toward distant hills. A weathered stone marker bears faded carvings indicating directions to various settlements, while scattered white flower petals and polished pebbles around its base suggest recent offerings to Selenara. The packed earth shows the heavy ruts of merchant wagons and the lighter tracks of horses, speaking to the steady flow of trade along this route. A gentle breeze carries the scent of dust and distant woodsmoke from some unseen settlement.`;
    this.setMapCoordinates({ x: 16, y: 2, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('road');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/west_road/room_16_1_0');
    this.addExit('south', '/areas/valdoria/west_road/room_16_3_0');
    this.addExit('east', '/areas/valdoria/west_road/room_17_2_0');
    this.addExit('west', '/areas/valdoria/west_road/room_15_2_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_17_1_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_15_1_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_17_3_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_15_3_0');

    // NPCs
    this.setNpcs(['/areas/valdoria/west_road/caravan_guard']);
  }
}

export default Room1620;
