/**
 * a windswept stretch of the Western Road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.085Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1740 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a windswept stretch of the Western Road';
    this.longDesc = `You stand upon a well-worn dirt road that cuts through rolling grasslands, its packed earth bearing the marks of countless travelers and merchant caravans. Golden prairie grass sways gently in Moradin's breath on either side of the path, creating waves that ripple toward the distant horizon. The air carries the earthy scent of sun-warmed soil and wild herbs, while scattered wildflowers dot the landscape in splashes of purple and white. To the west, the road continues its steady journey through this peaceful pastoral expanse.`;
    this.setMapCoordinates({ x: 17, y: 4, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/west_road/room_17_3_0');
    this.addExit('east', '/areas/valdoria/west_road/room_18_4_0');
    this.addExit('west', '/areas/valdoria/west_road/room_16_4_0');
    this.addExit('south', '/areas/valdoria/west_road/room_17_5_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_16_3_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_18_3_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_16_5_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_18_5_0');

  }
}

export default Room1740;
