/**
 * A worn dirt road beneath moonlight
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.092Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1610 extends Room {
  constructor() {
    super();
    this.shortDesc = 'A worn dirt road beneath moonlight';
    this.longDesc = `You stand upon a well-traveled dirt road that stretches endlessly in both directions, its packed earth marked by countless wagon wheels and hoofprints. Pale moonlight filters through wispy clouds above, casting shifting shadows across the rutted path where small stones glint like scattered stars. The air carries the faint scent of dust and distant woodsmoke, while the gentle night breeze whispers of journeys yet to come.`;
    this.setMapCoordinates({ x: 16, y: 1, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('road');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/west_road/room_16_0_0');
    this.addExit('south', '/areas/valdoria/west_road/room_16_2_0');
    this.addExit('east', '/areas/valdoria/west_road/room_17_1_0');
    this.addExit('west', '/areas/valdoria/west_road/room_15_1_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_17_0_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_15_0_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_17_2_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_15_2_0');

    // NPCs
    this.setNpcs(['/areas/valdoria/west_road/caravan_master', '/areas/valdoria/west_road/brother_mace']);
  }
}

export default Room1610;
