/**
 * a windswept stretch of the Western Road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.093Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1910 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a windswept stretch of the Western Road';
    this.longDesc = `You stand upon a well-traveled dirt road that cuts through rolling grasslands, its packed earth worn smooth by countless wagon wheels and travelers' boots. Golden prairie grass sways gently in the breeze on either side of the path, creating a sea of amber that stretches toward distant hills. The air carries the earthy scent of dust and wild flowers, while overhead, wispy clouds drift lazily across the endless sky. Wagon ruts and hoofprints in the dirt tell tales of merchants, adventurers, and pilgrims who have passed this way before you.`;
    this.setMapCoordinates({ x: 19, y: 1, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('south', '/areas/valdoria/west_road/room_19_2_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_18_0_0');
    this.addExit('west', '/areas/valdoria/west_road/room_18_1_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_18_2_0');

  }
}

export default Room1910;
