/**
 * A bend in the dusty western road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.083Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1450 extends Room {
  constructor() {
    super();
    this.shortDesc = 'A bend in the dusty western road';
    this.longDesc = `You stand where the Western Road curves gently through rolling grasslands, its packed dirt surface worn smooth by countless travelers. Tall prairie grasses sway in the breeze on either side of the path, their golden heads catching the light like scattered coins. The air carries the earthy scent of dust and wildflowers, while distant hills shimmer in the haze beyond the endless expanse of green.`;
    this.setMapCoordinates({ x: 14, y: 5, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/west_road/room_14_4_0');
    this.addExit('east', '/areas/valdoria/west_road/room_15_5_0');
    this.addExit('west', '/areas/valdoria/west_road/room_13_5_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_13_4_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_15_4_0');

  }
}

export default Room1450;
