/**
 * a weathered stretch of western road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.080Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1430 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a weathered stretch of western road';
    this.longDesc = `You stand upon a well-traveled dirt road that stretches endlessly toward the western horizon, its packed earth scarred by countless wagon wheels and boot prints. Pale stones mark the roadside at regular intervals, some bearing the crescent symbol of Selenara to guide night travelers safely on their journey. The air carries the faint scent of dust and distant woodsmoke, while deep ruts in the road speak of heavy merchant caravans that have passed this way recently.`;
    this.setMapCoordinates({ x: 14, y: 3, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('road');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('east', '/areas/valdoria/west_road/room_15_3_0');
    this.addExit('west', '/areas/valdoria/west_road/room_13_3_0');
    this.addExit('south', '/areas/valdoria/west_road/room_14_4_0');
    this.addExit('north', '/areas/valdoria/west_road/room_14_2_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_13_2_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_15_2_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_15_4_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_13_4_0');

  }
}

export default Room1430;
