/**
 * A weathered stretch of the Western Road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.079Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1630 extends Room {
  constructor() {
    super();
    this.shortDesc = 'A weathered stretch of the Western Road';
    this.longDesc = `You stand upon a well-traveled dirt road that stretches westward through rolling hills dotted with sparse woodland. Deep wagon ruts mark the passage of countless merchant caravans, while weathered stones placed at regular intervals serve as crude mile markers. The air carries the faint scent of dust and horse sweat, and you notice small white flowers scattered along the roadside - offerings left by travelers seeking Selenara's protection on their journeys. In the distance, the road curves gently around a low hill crowned with ancient oak trees.`;
    this.setMapCoordinates({ x: 16, y: 3, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('road');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/west_road/room_16_2_0');
    this.addExit('south', '/areas/valdoria/west_road/room_16_4_0');
    this.addExit('east', '/areas/valdoria/west_road/room_17_3_0');
    this.addExit('west', '/areas/valdoria/west_road/room_15_3_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_17_2_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_15_2_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_17_4_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_15_4_0');

    // NPCs
    this.setNpcs(['/areas/valdoria/west_road/calla']);
  }
}

export default Room1630;
