/**
 * a grassy meadow beside the dirt road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.094Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1500 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a grassy meadow beside the dirt road';
    this.longDesc = `You stand in a peaceful meadow where tall grass sways gently in Moradin's eternal breath. The Western Road stretches alongside this verdant expanse, its packed earth worn smooth by countless travelers seeking distant horizons. Wildflowers dot the grassland in scattered patches of color, while the sweet scent of prairie blooms mingles with the dust from the well-traveled path. In the distance, you can hear the faint whisper of wind through the grass, carrying with it the promise of adventure beyond.`;
    this.setMapCoordinates({ x: 15, y: 0, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('south', '/areas/valdoria/west_road/room_15_1_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_14_1_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_16_1_0');
    this.addExit('west', '/areas/valdoria/west_road/room_14_0_0');
    this.addExit('east', '/areas/valdoria/west_road/room_16_0_0');

  }
}

export default Room1500;
