/**
 * a grassy stretch beside the dirt road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.081Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1310 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a grassy stretch beside the dirt road';
    this.longDesc = `You stand on a gentle slope of grassland that borders the well-worn Western Road. The dirt path stretches endlessly in both directions, marked by countless wagon wheels and travelers' boots. Wild grasses sway in the breeze, their emerald blades catching the light as they whisper secrets to the wind that carries Moradin's ancient breath.`;
    this.setMapCoordinates({ x: 13, y: 1, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('south', '/areas/valdoria/west_road/room_13_2_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_14_0_0');
    this.addExit('east', '/areas/valdoria/west_road/room_14_1_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_14_2_0');

  }
}

export default Room1310;
