/**
 * a worn stretch of the Western Road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.091Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1920 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a worn stretch of the Western Road';
    this.longDesc = `You stand upon a well-traveled dirt road that cuts through rolling grasslands, its packed earth bearing the marks of countless wagon wheels and hoofprints. Tall prairie grasses sway gently on either side of the path, their golden tips catching the light as they whisper secrets to the wind that carries Moradin's breath across the land. The road stretches onward through the peaceful countryside, worn smooth by generations of travelers seeking their fortunes in distant lands.`;
    this.setMapCoordinates({ x: 19, y: 2, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('south', '/areas/valdoria/west_road/room_19_3_0');
    this.addExit('north', '/areas/valdoria/west_road/room_19_1_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_18_1_0');
    this.addExit('west', '/areas/valdoria/west_road/room_18_2_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_18_3_0');

  }
}

export default Room1920;
