/**
 * a weathered stretch of the Western Road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.087Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1550 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a weathered stretch of the Western Road';
    this.longDesc = `You stand upon a well-traveled section of the Western Road, where countless wagon wheels and hoofbeats have worn deep ruts into the packed earth. Wild grasses sway gently on either side of the dirt path, their emerald blades catching the light as they bend in Moradin's eternal breath. The road stretches onward through the grasslands, marked by occasional stone mile markers that speak of distant destinations and the dreams of travelers who have passed this way.`;
    this.setMapCoordinates({ x: 15, y: 5, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/west_road/room_15_4_0');
    this.addExit('east', '/areas/valdoria/west_road/room_16_5_0');
    this.addExit('west', '/areas/valdoria/west_road/room_14_5_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_14_4_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_16_4_0');

  }
}

export default Room1550;
