/**
 * a windswept meadow beside the dirt road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.088Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1950 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a windswept meadow beside the dirt road';
    this.longDesc = `You stand in a rolling meadow of tall grass that sways gently in the constant western breeze. The packed dirt of the Western Road cuts through the landscape nearby, its well-worn surface marked by countless wagon wheels and traveler's boots. Wildflowers dot the grassland in scattered patches of color, while the sweet scent of prairie herbs mingles with the dusty smell of the road.`;
    this.setMapCoordinates({ x: 19, y: 5, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/west_road/room_19_4_0');
    this.addExit('west', '/areas/valdoria/west_road/room_18_5_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_18_4_0');

  }
}

export default Room1950;
