/**
 * A dusty crossroads beneath moonlit skies
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.080Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1330 extends Room {
  constructor() {
    super();
    this.shortDesc = 'A dusty crossroads beneath moonlit skies';
    this.longDesc = `You stand at a weathered crossroads where the Western Road branches into smaller dirt paths leading toward distant settlements. Pale moonlight filters through wispy clouds above, casting silver shadows across the packed earth and illuminating small piles of white stones left by travelers as offerings to Selenara. The air carries the faint scent of dust and distant woodsmoke, while the soft hooting of an owl echoes from the darkness beyond the road's edge.`;
    this.setMapCoordinates({ x: 13, y: 3, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('road');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('east', '/areas/valdoria/west_road/room_14_3_0');
    this.addExit('south', '/areas/valdoria/west_road/room_13_4_0');
    this.addExit('north', '/areas/valdoria/west_road/room_13_2_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_14_2_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_14_4_0');

  }
}

export default Room1330;
