/**
 * a grassy meadow beside the dirt road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.084Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1540 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a grassy meadow beside the dirt road';
    this.longDesc = `You stand in a peaceful stretch of grassland where wildflowers dot the emerald carpet beneath your feet. The Western Road curves gently through this meadow, its packed earth worn smooth by countless travelers and merchant caravans. A warm breeze carries the sweet scent of clover and distant woodlands, while the rhythmic chirping of crickets creates a soothing melody. To the west, the road disappears over a gentle hill crowned with swaying grass.`;
    this.setMapCoordinates({ x: 15, y: 4, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/west_road/room_15_3_0');
    this.addExit('east', '/areas/valdoria/west_road/room_16_4_0');
    this.addExit('west', '/areas/valdoria/west_road/room_14_4_0');
    this.addExit('south', '/areas/valdoria/west_road/room_15_5_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_14_3_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_16_3_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_14_5_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_16_5_0');

  }
}

export default Room1540;
