/**
 * a windswept stretch of the Western Road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.090Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1720 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a windswept stretch of the Western Road';
    this.longDesc = `You stand upon a well-traveled dirt road that cuts through rolling grasslands, its packed earth marked by countless wagon wheels and hoofprints. Golden prairie grass sways gently on either side of the path, stretching toward distant horizons where wildflowers dot the landscape in scattered patches of color. The wind carries the earthy scent of dust and wild herbs, while overhead, puffy white clouds drift lazily across an endless blue sky. To the west, the road continues its steady path toward whatever destinations await beyond the grassland's gentle embrace.`;
    this.setMapCoordinates({ x: 17, y: 2, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('south', '/areas/valdoria/west_road/room_17_3_0');
    this.addExit('north', '/areas/valdoria/west_road/room_17_1_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_16_1_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_18_1_0');
    this.addExit('east', '/areas/valdoria/west_road/room_18_2_0');
    this.addExit('west', '/areas/valdoria/west_road/room_16_2_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_18_3_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_16_3_0');

  }
}

export default Room1720;
