/**
 * a grassy meadow beside the dirt road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.088Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1850 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a grassy meadow beside the dirt road';
    this.longDesc = `You stand in a gentle meadow where wild grass sways in Moradin's eternal breath, the emerald blades dotted with tiny wildflowers that seem to pulse faintly with the heartbeat of magic itself. The packed dirt of the Western Road cuts through this pastoral scene like a brown ribbon, worn smooth by countless travelers seeking their fortunes. A sweet fragrance of clover and earth fills the air, while the distant sound of wind through grass creates nature's own whispered song.`;
    this.setMapCoordinates({ x: 18, y: 5, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/west_road/room_18_4_0');
    this.addExit('east', '/areas/valdoria/west_road/room_19_5_0');
    this.addExit('west', '/areas/valdoria/west_road/room_17_5_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_17_4_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_19_4_0');

  }
}

export default Room1850;
