/**
 * a grassy meadow beside the dirt road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.088Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1420 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a grassy meadow beside the dirt road';
    this.longDesc = `You stand in a peaceful stretch of grassland that borders the well-traveled Western Road. The dirt path cuts through the emerald meadow like a brown ribbon, worn smooth by countless boots, hooves, and wagon wheels. Wildflowers dot the swaying grass in splashes of yellow and purple, while the gentle breeze carries the earthy scent of the road mixed with the sweet fragrance of prairie blooms. To the east, the road continues its winding journey toward distant settlements.`;
    this.setMapCoordinates({ x: 14, y: 2, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('south', '/areas/valdoria/west_road/room_14_3_0');
    this.addExit('north', '/areas/valdoria/west_road/room_14_1_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_13_1_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_15_1_0');
    this.addExit('east', '/areas/valdoria/west_road/room_15_2_0');
    this.addExit('west', '/areas/valdoria/west_road/room_13_2_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_15_3_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_13_3_0');

  }
}

export default Room1420;
