/**
 * a grassy bend in the dirt road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.087Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1650 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a grassy bend in the dirt road';
    this.longDesc = `You stand where the Western Road curves gently through rolling grassland, its packed earth worn smooth by countless travelers. Wild grasses sway in the breeze on either side of the path, their green blades catching the light like scattered emeralds. The road stretches onward through the pastoral landscape, disappearing over distant hills beneath an open sky.`;
    this.setMapCoordinates({ x: 16, y: 5, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/west_road/room_16_4_0');
    this.addExit('east', '/areas/valdoria/west_road/room_17_5_0');
    this.addExit('west', '/areas/valdoria/west_road/room_15_5_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_15_4_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_17_4_0');

  }
}

export default Room1650;
