/**
 * a grassy meadow beside the dirt road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.083Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1350 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a grassy meadow beside the dirt road';
    this.longDesc = `You stand in a gentle meadow where wild grasses sway in Moradin's eternal breath, their emerald blades catching the light that filters through scattered clouds above. The Western Road cuts a dusty brown ribbon through this pastoral scene, its well-worn earth speaking of countless travelers who have passed this way. Wildflowers dot the grassland in splashes of color, and you can hear the distant sound of wagon wheels and hoofbeats echoing from both directions along the thoroughfare.`;
    this.setMapCoordinates({ x: 13, y: 5, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/west_road/room_13_4_0');
    this.addExit('east', '/areas/valdoria/west_road/room_14_5_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_14_4_0');

  }
}

export default Room1350;
