/**
 * a windswept stretch of the Western Road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.086Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1840 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a windswept stretch of the Western Road';
    this.longDesc = `You stand upon a well-traveled dirt road that cuts through rolling grasslands, its packed earth worn smooth by countless wagon wheels and weary travelers. Golden prairie grass sways gently in Moradin's eternal breath, stretching endlessly toward distant horizons where sky meets earth. The road continues its steady westward journey, marked by occasional stone mile markers weathered by time and elements. A sense of wanderlust fills the air, as if the very path itself calls to those seeking adventure beyond the settled lands.`;
    this.setMapCoordinates({ x: 18, y: 4, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/west_road/room_18_3_0');
    this.addExit('east', '/areas/valdoria/west_road/room_19_4_0');
    this.addExit('west', '/areas/valdoria/west_road/room_17_4_0');
    this.addExit('south', '/areas/valdoria/west_road/room_18_5_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_17_3_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_19_3_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_17_5_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_19_5_0');

  }
}

export default Room1840;
