/**
 * A dusty crossroads beneath moonlit sky
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.093Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1710 extends Room {
  constructor() {
    super();
    this.shortDesc = 'A dusty crossroads beneath moonlit sky';
    this.longDesc = `You stand at a weathered crossroads where the Western Road splits into three distinct paths, each marked by ancient stone markers worn smooth by countless travelers. White wildflowers grow in scattered clusters along the roadside, their pale petals seeming to glow in the silvery moonlight that filters through wispy clouds above. The air carries the faint scent of dust and distant campfires, while polished stones glint mysteriously at the base of each directional marker - offerings left by faithful travelers seeking Selenara's protection on their journeys.`;
    this.setMapCoordinates({ x: 17, y: 1, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('road');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/west_road/room_17_0_0');
    this.addExit('south', '/areas/valdoria/west_road/room_17_2_0');
    this.addExit('east', '/areas/valdoria/west_road/room_18_1_0');
    this.addExit('west', '/areas/valdoria/west_road/room_16_1_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_18_0_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_16_0_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_18_2_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_16_2_0');

    // NPCs
    this.setNpcs(['/areas/valdoria/west_road/caravan_quartermaster', '/areas/valdoria/west_road/spice_trader']);
  }
}

export default Room1710;
