/**
 * a windswept stretch of the Western Road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.095Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1400 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a windswept stretch of the Western Road';
    this.longDesc = `You stand upon a well-traveled dirt road that cuts through rolling grasslands, its packed earth worn smooth by countless feet, hooves, and wagon wheels. Golden prairie grass sways gently on either side of the path, rustling with the whispered songs that Moradin's breath carries across the open plains. The road stretches endlessly westward, disappearing into the hazy distance where sky meets earth in an endless dance of possibility.`;
    this.setMapCoordinates({ x: 14, y: 0, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('south', '/areas/valdoria/west_road/room_14_1_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_13_1_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_15_1_0');
    this.addExit('east', '/areas/valdoria/west_road/room_15_0_0');

  }
}

export default Room1400;
