/**
 * A bend in the dusty western road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.086Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1940 extends Room {
  constructor() {
    super();
    this.shortDesc = 'A bend in the dusty western road';
    this.longDesc = `You stand at a gentle curve in the Western Road, where the packed dirt path winds through rolling grassland dotted with wildflowers. The sweet scent of prairie grass mingles with the earthy smell of the well-traveled road, while a warm breeze carries distant sounds of travelers and merchants. To either side, the emerald grassland stretches toward the horizon, broken only by the occasional weathered milestone marking distances to far-off settlements.`;
    this.setMapCoordinates({ x: 19, y: 4, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/west_road/room_19_3_0');
    this.addExit('west', '/areas/valdoria/west_road/room_18_4_0');
    this.addExit('south', '/areas/valdoria/west_road/room_19_5_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_18_3_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_18_5_0');

  }
}

export default Room1940;
