/**
 * A windswept stretch of the Western Road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.084Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1440 extends Room {
  constructor() {
    super();
    this.shortDesc = 'A windswept stretch of the Western Road';
    this.longDesc = `You stand upon a well-traveled dirt road that cuts through rolling grasslands dotted with wildflowers. The packed earth beneath your feet bears the marks of countless wagon wheels and hoofprints, while tall grass sways gently on either side in Moradin's eternal breath. To the west, the road continues its winding path toward distant horizons, and you can smell the sweet scent of prairie blooms carried on the wind.`;
    this.setMapCoordinates({ x: 14, y: 4, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/west_road/room_14_3_0');
    this.addExit('east', '/areas/valdoria/west_road/room_15_4_0');
    this.addExit('west', '/areas/valdoria/west_road/room_13_4_0');
    this.addExit('south', '/areas/valdoria/west_road/room_14_5_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_13_3_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_15_3_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_13_5_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_15_5_0');

  }
}

export default Room1440;
