/**
 * A bend in the dusty western road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.095Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1800 extends Room {
  constructor() {
    super();
    this.shortDesc = 'A bend in the dusty western road';
    this.longDesc = `You stand where the Western Road curves gently through rolling grasslands, its packed dirt surface worn smooth by countless travelers and merchant caravans. Tall prairie grasses sway in the breeze on either side of the path, their golden heads catching the light like waves on a verdant sea. The air carries the earthy scent of sun-warmed soil and wildflowers, while distant hills rise like sleeping giants against the horizon. Wheel ruts and hoof prints in the dirt speak of the road's constant use by those seeking fortune or adventure in the lands beyond.`;
    this.setMapCoordinates({ x: 18, y: 0, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('south', '/areas/valdoria/west_road/room_18_1_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_17_1_0');
    this.addExit('west', '/areas/valdoria/west_road/room_17_0_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_19_1_0');

  }
}

export default Room1800;
