/**
 * Western Road Entrance at Moonlit Crossroads
 *
 * Generated by Area Builder on 2026-01-25T06:13:23.507Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1930 extends Room {
  constructor() {
    super();
    this.shortDesc = 'Western Road Entrance at Moonlit Crossroads';
    this.longDesc = `You stand at the weathered entrance to the Western Road, where packed earth gives way to well-traveled dirt that stretches into the distance. A worn stone marker bears the carved symbol of crossed paths beneath Selenara's crescent moon, its surface polished smooth by countless travelers' hands seeking the goddess's blessing. The air carries the scent of dust and distant woodsmoke, while white wildflowers cluster around the marker's base - offerings left by previous wayfarers. Deep wagon ruts and hoof prints in the hardened earth speak of the constant flow of merchants and pilgrims who pass through this threshold between civilization and the wild roads beyond.`;
    this.setMapCoordinates({ x: 19, y: 3, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('road');
    this.setupRoom();  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/west_road/room_19_2_0');
    this.addExit('west', '/areas/valdoria/west_road/room_18_3_0');
    this.addExit('south', '/areas/valdoria/west_road/room_19_4_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_18_2_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_18_4_0');
    this.addExit('east', '/areas/valdoria/aldric/room_0_2_0');

  }
}

export default Room1930;
