/**
 * a grassy meadow beside the dirt road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.082Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1340 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a grassy meadow beside the dirt road';
    this.longDesc = `You stand in a stretch of verdant grassland that borders the well-traveled Western Road. The packed dirt path cuts through the rolling green expanse, worn smooth by countless merchant wagons and travelers' feet. Wildflowers dot the meadow in scattered clusters of yellow and white, swaying gently in the breeze that carries the earthy scent of sun-warmed soil. To the west, the road continues its winding journey toward distant horizons.`;
    this.setMapCoordinates({ x: 13, y: 4, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/west_road/room_13_3_0');
    this.addExit('south', '/areas/valdoria/west_road/room_13_5_0');
    this.addExit('east', '/areas/valdoria/west_road/room_14_4_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_14_3_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_14_5_0');

  }
}

export default Room1340;
