/**
 * A weathered stretch of the Western Road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.080Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1530 extends Room {
  constructor() {
    super();
    this.shortDesc = 'A weathered stretch of the Western Road';
    this.longDesc = `You stand on a well-traveled dirt road that stretches endlessly in both directions, its packed earth bearing the deep ruts of countless merchant wagons and the hoofprints of weary horses. Pale wildflowers dot the grassy verges on either side, their white petals seeming to glow faintly in the light as if blessed by Selenara's touch. The air carries the dusty scent of the road mixed with the sweet fragrance of the roadside blooms, while distant wheel ruts suggest this stretch sees regular use by the merchant caravans that ply the western trade routes.`;
    this.setMapCoordinates({ x: 15, y: 3, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('road');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('east', '/areas/valdoria/west_road/room_16_3_0');
    this.addExit('west', '/areas/valdoria/west_road/room_14_3_0');
    this.addExit('south', '/areas/valdoria/west_road/room_15_4_0');
    this.addExit('north', '/areas/valdoria/west_road/room_15_2_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_14_2_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_16_2_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_16_4_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_14_4_0');

  }
}

export default Room1530;
