/**
 * A grassy meadow beside the Western Road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.085Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1640 extends Room {
  constructor() {
    super();
    this.shortDesc = 'A grassy meadow beside the Western Road';
    this.longDesc = `You stand in a peaceful stretch of grassland that borders the well-worn Western Road to your south. The dirt path cuts through the verdant meadow like a brown ribbon, its surface packed hard by countless travelers and merchant caravans. Wildflowers dot the emerald grass around you, swaying gently in Moradin's eternal breath, while the distant sound of wagon wheels and hoofbeats drifts from the road below.`;
    this.setMapCoordinates({ x: 16, y: 4, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/west_road/room_16_3_0');
    this.addExit('east', '/areas/valdoria/west_road/room_17_4_0');
    this.addExit('west', '/areas/valdoria/west_road/room_15_4_0');
    this.addExit('south', '/areas/valdoria/west_road/room_16_5_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_15_3_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_17_3_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_15_5_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_17_5_0');

  }
}

export default Room1640;
