/**
 * a windswept stretch of the Western Road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.088Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1750 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a windswept stretch of the Western Road';
    this.longDesc = `You stand upon a well-worn dirt road that cuts through rolling grasslands, its packed earth bearing the marks of countless travelers and merchant caravans. Golden prairie grass sways gently in Moradin's eternal breath, whispering secrets to those who pause to listen. The road stretches endlessly in both directions, a ribbon of earthen brown against the emerald sea of grass that extends to the distant horizon.`;
    this.setMapCoordinates({ x: 17, y: 5, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/west_road/room_17_4_0');
    this.addExit('east', '/areas/valdoria/west_road/room_18_5_0');
    this.addExit('west', '/areas/valdoria/west_road/room_16_5_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_16_4_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_18_4_0');

  }
}

export default Room1750;
