/**
 * a windswept stretch of the Western Road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.081Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1320 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a windswept stretch of the Western Road';
    this.longDesc = `You stand upon a well-traveled dirt road that cuts through rolling grasslands, its packed earth worn smooth by countless wagon wheels and footsteps. Golden prairie grass sways gently in the breeze on either side of the path, creating a sea of movement that stretches to the horizon. The air carries the sweet scent of wildflowers and distant rain, while the road itself bears the dusty evidence of recent travelers heading both east and west.`;
    this.setMapCoordinates({ x: 13, y: 2, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('south', '/areas/valdoria/west_road/room_13_3_0');
    this.addExit('north', '/areas/valdoria/west_road/room_13_1_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_14_1_0');
    this.addExit('east', '/areas/valdoria/west_road/room_14_2_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_14_3_0');

  }
}

export default Room1320;
