/**
 * a windswept stretch of the Western Road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.093Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1810 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a windswept stretch of the Western Road';
    this.longDesc = `You stand upon a well-worn dirt road that cuts through rolling grasslands, its packed earth bearing the marks of countless travelers who have journeyed westward. The gentle breeze carries the sweet scent of wildflowers and prairie grass, while distant hills shimmer in the haze beyond the endless expanse of green. Weathered wooden posts mark the roadside at irregular intervals, their surfaces carved with directional symbols and travelers' marks from ages past.`;
    this.setMapCoordinates({ x: 18, y: 1, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('south', '/areas/valdoria/west_road/room_18_2_0');
    this.addExit('north', '/areas/valdoria/west_road/room_18_0_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_17_0_0');
    this.addExit('east', '/areas/valdoria/west_road/room_19_1_0');
    this.addExit('west', '/areas/valdoria/west_road/room_17_1_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_19_2_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_17_2_0');

  }
}

export default Room1810;
