/**
 * A moonlit stretch of the Western Road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.078Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1830 extends Room {
  constructor() {
    super();
    this.shortDesc = 'A moonlit stretch of the Western Road';
    this.longDesc = `You stand upon a well-traveled dirt road that stretches endlessly into the western horizon, its packed earth bearing the countless wheel ruts and hoof prints of merchant caravans. Pale moonlight filters through scattered clouds above, casting shifting shadows across the path and illuminating small shrines of white flowers and polished stones left at the roadside by faithful travelers seeking Selenara's protection. The air carries the faint scent of dust and distant campfires, while the soft sound of night wind whispers through the sparse grass that borders this lonely stretch of the trade route.`;
    this.setMapCoordinates({ x: 18, y: 3, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('road');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('east', '/areas/valdoria/west_road/room_19_3_0');
    this.addExit('west', '/areas/valdoria/west_road/room_17_3_0');
    this.addExit('south', '/areas/valdoria/west_road/room_18_4_0');
    this.addExit('north', '/areas/valdoria/west_road/room_18_2_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_17_2_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_19_2_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_19_4_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_17_4_0');

  }
}

export default Room1830;
