/**
 * a worn stretch of the Western Road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.089Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1520 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a worn stretch of the Western Road';
    this.longDesc = `You stand upon a well-traveled dirt road that cuts through rolling grasslands, its packed earth bearing the marks of countless wagon wheels and boot prints. Tall prairie grasses sway gently on either side of the path, their golden heads catching the light as they whisper secrets to the wind. The road stretches onward through the verdant landscape, worn smooth by generations of travelers seeking their fortunes in distant lands. A faint scent of wildflowers and dust hangs in the air, carried by Moradin's eternal breath across the open plains.`;
    this.setMapCoordinates({ x: 15, y: 2, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('south', '/areas/valdoria/west_road/room_15_3_0');
    this.addExit('north', '/areas/valdoria/west_road/room_15_1_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_14_1_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_16_1_0');
    this.addExit('east', '/areas/valdoria/west_road/room_16_2_0');
    this.addExit('west', '/areas/valdoria/west_road/room_14_2_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_16_3_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_14_3_0');

  }
}

export default Room1520;
