/**
 * A weathered stretch of the Western Road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.092Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1510 extends Room {
  constructor() {
    super();
    this.shortDesc = 'A weathered stretch of the Western Road';
    this.longDesc = `You stand upon a well-traveled dirt road that cuts through the rolling countryside, its packed earth marked by countless wagon wheels and hoofprints. Ancient stone markers bearing the crescent symbol of Selenara stand at regular intervals along the roadside, their surfaces polished smooth by generations of travelers seeking the Moon Goddess's protection. The western horizon stretches endlessly before you, while scattered white wildflowers bloom in the roadside grass - offerings left by the faithful that have taken root and flourished.`;
    this.setMapCoordinates({ x: 15, y: 1, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('road');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('north', '/areas/valdoria/west_road/room_15_0_0');
    this.addExit('south', '/areas/valdoria/west_road/room_15_2_0');
    this.addExit('east', '/areas/valdoria/west_road/room_16_1_0');
    this.addExit('west', '/areas/valdoria/west_road/room_14_1_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_16_0_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_14_0_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_16_2_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_14_2_0');

    // NPCs
    this.setNpcs(['/areas/valdoria/west_road/caravan_scout', '/areas/valdoria/west_road/textile_trader', '/areas/valdoria/west_road/trader_metal', '/areas/valdoria/west_road/caravan_cook']);
  }
}

export default Room1510;
