/**
 * a weathered crossroads on the western road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.078Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1730 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a weathered crossroads on the western road';
    this.longDesc = `You stand at a dusty crossroads where the main western road intersects with a smaller dirt path heading north toward distant hills. A weathered wooden signpost leans at an odd angle, its carved directions barely legible after years of wind and rain. Small white stones and wilted flowers scattered around the post's base suggest travelers have left offerings here, perhaps seeking Selenara's protection for their journeys. The packed earth shows the tracks of countless wagon wheels, hoofprints, and boots that have passed this way.`;
    this.setMapCoordinates({ x: 17, y: 3, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('road');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('east', '/areas/valdoria/west_road/room_18_3_0');
    this.addExit('west', '/areas/valdoria/west_road/room_16_3_0');
    this.addExit('south', '/areas/valdoria/west_road/room_17_4_0');
    this.addExit('north', '/areas/valdoria/west_road/room_17_2_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_16_2_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_18_2_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_18_4_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_16_4_0');

  }
}

export default Room1730;
