/**
 * a dusty crossroads on the western road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.094Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1600 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a dusty crossroads on the western road';
    this.longDesc = `You stand at a weathered crossroads where the packed dirt of the Western Road meets rolling grasslands that stretch endlessly toward the horizon. Wildflowers dot the emerald expanse, their petals dancing in the gentle breeze that carries the earthy scent of sun-warmed soil. Deep wagon ruts mark the well-traveled path, while scattered stones along the roadside bear the smooth polish of countless travelers who have paused here to rest. The vast sky above seems to pulse with an almost imperceptible rhythm, as if echoing the divine heartbeat that flows through all creation.`;
    this.setMapCoordinates({ x: 16, y: 0, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('south', '/areas/valdoria/west_road/room_16_1_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_15_1_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_17_1_0');
    this.addExit('west', '/areas/valdoria/west_road/room_15_0_0');
    this.addExit('east', '/areas/valdoria/west_road/room_17_0_0');

  }
}

export default Room1600;
