/**
 * a windswept stretch of the Western Road
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.091Z
 * Area: The Western Road (valdoria:west_road)
 */

import { Room } from '../../../lib/std.js';

export class Room1820 extends Room {
  constructor() {
    super();
    this.shortDesc = 'a windswept stretch of the Western Road';
    this.longDesc = `You stand upon a well-worn dirt road that cuts through rolling grasslands, its packed earth bearing the marks of countless travelers who have journeyed west. Golden prairie grass sways gently in the breeze on either side of the path, creating waves that ripple toward the distant horizon. The air carries the sweet scent of wildflowers and sun-warmed earth, while overhead, wispy clouds drift lazily across an endless sky. Far to the west, you can make out the faint outline of hills where the road seems to disappear into the shimmering heat.`;
    this.setMapCoordinates({ x: 18, y: 2, z: 0, area: '/areas/valdoria/west_road' });
    this.setTerrain('grassland');
    this.setupRoom();
  }

  private setupRoom(): void {
    // Exits
    this.addExit('south', '/areas/valdoria/west_road/room_18_3_0');
    this.addExit('north', '/areas/valdoria/west_road/room_18_1_0');
    this.addExit('northwest', '/areas/valdoria/west_road/room_17_1_0');
    this.addExit('northeast', '/areas/valdoria/west_road/room_19_1_0');
    this.addExit('east', '/areas/valdoria/west_road/room_19_2_0');
    this.addExit('west', '/areas/valdoria/west_road/room_17_2_0');
    this.addExit('southeast', '/areas/valdoria/west_road/room_19_3_0');
    this.addExit('southwest', '/areas/valdoria/west_road/room_17_3_0');

  }
}

export default Room1820;
