/**
 * A trader, dealing in textiles.
 *
 * Generated by Area Builder on 2026-01-23T03:43:06.097Z
 * Area: The Western Road (valdoria:west_road)
 */

import { NPC } from '../../../lib/std.js';

export class TextileTrader extends NPC {
  constructor() {
    super();
    this.name = 'A trader, dealing in textiles.';
    this.shortDesc = 'a weathered textile merchant with calloused hands';
    this.longDesc = `This road-worn trader bears the marks of countless journeys along the dusty western routes, their neutral features sun-darkened and eyes sharp with the wisdom of one who has bargained in a dozen different tongues. Bolts of fine cloth and sturdy canvas are carefully arranged in their pack, each piece selected for durability and appeal to the diverse settlements scattered along these remote paths. Their fingers move with practiced ease through samples of wool, silk, and linen, assessing quality with the touch of someone who has built their livelihood on knowing good thread from poor.`;
    this.level = 8;
    this.maxHealth = 50;
    this.health = 50;
    this.gender = 'male';
    this.keywords = ['trader', 'textile trader'];
    this.wandering = false;
    this.respawnTime = 0;
  }
}

export default TextileTrader;
